package validationrules.probate;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.ActorIdType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.Classification;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.CaseWorkerAccessProfile;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.Jurisdiction;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.crd.JobTitle;
import java.util.ArrayList;
import  uk.gov.hmcts.reform.orgrolemapping.util.JacksonUtils;
import java.util.HashMap
import java.util.Map
import com.fasterxml.jackson.databind.JsonNode;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.FeatureFlag;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.FeatureFlagEnum;
import function uk.gov.hmcts.reform.orgrolemapping.domain.service.RequestMappingService.logMsg;

/*
 * PROBATE staff "senior-tribunal-caseworker" Org role mapping.
 */

rule "probate_senior_tribunal_caseworker_v1"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PROBATE_WA_1_0.getValue())
  $up: CaseWorkerAccessProfile(hasValidJobTitle(JobTitle.SENIOR_LEGAL_CASEWORKER), 
                               hasValidServiceCode(Jurisdiction.PROBATE), !suspended)
then
   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode(Jurisdiction.PROBATE.getName()));
   attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($up.getPrimaryLocationId()));
  insert(
      RoleAssignment.builder()
      .actorIdType(ActorIdType.IDAM)
      .actorId($up.getId())
      .roleCategory(RoleCategory.LEGAL_OPERATIONS)
      .roleType(RoleType.ORGANISATION)
      .roleName(RoleName.SENIOR_TRIBUNAL_CASEWORKER)
      .grantType(GrantType.STANDARD)
      .classification(Classification.PUBLIC)
      .readOnly(false)
      .attributes(attribute)
      .authorisations($up.getSkillCodes())
      .build());
      logMsg("Rule : probate_senior_tribunal_caseworker_v1");
end;

/*
 * PROBATE staff "tribunal-caseworker" Org role mapping.
 */

rule "probate_tribunal_caseworker_v1"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PROBATE_WA_1_0.getValue())
  $up: CaseWorkerAccessProfile(hasValidJobTitle(JobTitle.SENIOR_LEGAL_CASEWORKER, JobTitle.LEGAL_CASEWORKER), 
                               hasValidServiceCode(Jurisdiction.PROBATE), !suspended)
then
   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode(Jurisdiction.PROBATE.getName()));
   attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($up.getPrimaryLocationId()));
   attribute.put("workTypes", JacksonUtils.convertObjectIntoJsonNode("decision_making_work"));
  insert(
      RoleAssignment.builder()
      .actorIdType(ActorIdType.IDAM)
      .actorId($up.getId())
      .roleCategory(RoleCategory.LEGAL_OPERATIONS)
      .roleType(RoleType.ORGANISATION)
      .roleName(RoleName.TRIBUNAL_CASEWORKER)
      .grantType(GrantType.STANDARD)
      .classification(Classification.PUBLIC)
      .readOnly(false)
      .attributes(attribute)
      .authorisations($up.getSkillCodes())
      .build());
      logMsg("Rule : probate_tribunal_caseworker_v1");
end;

/*
 * PROBATE staff "hmcts-legal-operations" Org role mapping.
 */

rule "probate_hmcts_legal_operations_v1"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PROBATE_WA_1_0.getValue())
  $up: CaseWorkerAccessProfile(hasValidJobTitle(JobTitle.SENIOR_LEGAL_CASEWORKER, JobTitle.LEGAL_CASEWORKER), 
                               hasValidServiceCode(Jurisdiction.PROBATE), !suspended)
then
   Map<String,JsonNode> attribute = new HashMap<>();
  insert(
      RoleAssignment.builder()
      .actorIdType(ActorIdType.IDAM)
      .actorId($up.getId())
      .roleCategory(RoleCategory.LEGAL_OPERATIONS)
      .roleType(RoleType.ORGANISATION)
      .roleName(RoleName.HMCTS_LEGAL_OPERATIONS)
      .grantType(GrantType.BASIC)
      .classification(Classification.PRIVATE)
      .readOnly(true)
      .attributes(attribute)
      .build());
      logMsg("Rule : probate_hmcts_legal_operations_v1");
end;

/*
 * PROBATE staff "task-supervisor" Org role mapping.
 */

rule "probate_task_supervisor_org_v1"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PROBATE_WA_1_0.getValue())
  $up: CaseWorkerAccessProfile(hasValidJobTitle(JobTitle.SENIOR_LEGAL_CASEWORKER, JobTitle.LEGAL_CASEWORKER), 
                               hasValidServiceCode(Jurisdiction.PROBATE), !suspended, isTaskSupervisor())
then
   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode(Jurisdiction.PROBATE.getName()));
   attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($up.getPrimaryLocationId()));
  insert(
      RoleAssignment.builder()
      .actorIdType(ActorIdType.IDAM)
      .actorId($up.getId())
      .roleCategory(RoleCategory.LEGAL_OPERATIONS)
      .roleType(RoleType.ORGANISATION)
      .roleName(RoleName.TASK_SUPERVISOR)
      .grantType(GrantType.STANDARD)
      .classification(Classification.PUBLIC)
      .readOnly(false)
      .attributes(attribute)
      .authorisations($up.getSkillCodes())
      .build());
      logMsg("Rule : probate_task_supervisor_org_v1");
end;

/*
 * PROBATE staff "case-allocator" Org role mapping.
 */

rule "probate_case_allocator_org_v1"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PROBATE_WA_1_0.getValue())
  $up: CaseWorkerAccessProfile(hasValidJobTitle(JobTitle.SENIOR_LEGAL_CASEWORKER, JobTitle.LEGAL_CASEWORKER), 
                               hasValidServiceCode(Jurisdiction.PROBATE), !suspended, isCaseAllocator())
then
   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode(Jurisdiction.PROBATE.getName()));
   attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($up.getPrimaryLocationId()));
  insert(
      RoleAssignment.builder()
      .actorIdType(ActorIdType.IDAM)
      .actorId($up.getId())
      .roleCategory(RoleCategory.LEGAL_OPERATIONS)
      .roleType(RoleType.ORGANISATION)
      .roleName(RoleName.CASE_ALLOCATOR)
      .grantType(GrantType.STANDARD)
      .classification(Classification.PUBLIC)
      .readOnly(false)
      .attributes(attribute)
      .authorisations($up.getSkillCodes())
      .build());
      logMsg("Rule : probate_case_allocator_org_v1");
end;

/*
 * PROBATE staff "specific-access-approver-legal-ops" Org role mapping.
 */

rule "probate_specific_access_approver_legal_ops_v1"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PROBATE_WA_1_0.getValue())
  $up: CaseWorkerAccessProfile(hasValidJobTitle(JobTitle.SENIOR_LEGAL_CASEWORKER), 
                               hasValidServiceCode(Jurisdiction.PROBATE), !suspended)
then
   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode(Jurisdiction.PROBATE.getName()));
   attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($up.getPrimaryLocationId()));
   attribute.put("workTypes", JacksonUtils.convertObjectIntoJsonNode("access_requests"));
  insert(
      RoleAssignment.builder()
      .actorIdType(ActorIdType.IDAM)
      .actorId($up.getId())
      .roleCategory(RoleCategory.LEGAL_OPERATIONS)
      .roleType(RoleType.ORGANISATION)
      .roleName(RoleName.SPECIFIC_ACCESS_APPROVER_LEGAL_OPS)
      .grantType(GrantType.STANDARD)
      .classification(Classification.PUBLIC)
      .readOnly(false)
      .attributes(attribute)
      .authorisations($up.getSkillCodes())
      .build());
      logMsg("Rule : probate_specific_access_approver_legal_ops_v1");
    end;

