package validationrules.test;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.JudicialAccessProfile;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.CaseWorkerAccessProfile;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.JudicialOfficeHolder;


rule "judicial_access_profile"
salience 1000
when
	$jap: JudicialAccessProfile()
then
	System.err.println("We have judicial access profile with appointment  " + $jap.getAppointment() + " : " + $jap);
end;

rule "caseworker_access_profile"
salience 1000
when
	$cap: CaseWorkerAccessProfile()
then
	System.err.println("We have caseworker access profile with roleId  " + $cap.getRoleId() + " : " + $cap);
end;

rule "role_assignment"
salience 1000
when
	$ra: RoleAssignment()
then
	System.err.println("We have role assignment " + $ra.getStatus() + " : " + $ra);
end;

rule "judicial_office_holder"
salience 1000
when
	$joh: JudicialOfficeHolder()
then
	System.err.println("We have a judicialOfficeHolder with role  " + $joh.getOffice() + " : " + $joh);
end;




