package validationrules.hrs;

import uk.gov.hmcts.reform.orgrolemapping.domain.model.CaseWorkerAccessProfile;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.FeatureFlag;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.constants.RoleAssignmentConstants.Attributes;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.constants.RoleAssignmentConstants.RoleName;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.ActorIdType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.Classification;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.FeatureFlagEnum;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.Jurisdiction;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.crd.JobTitle;
import uk.gov.hmcts.reform.orgrolemapping.util.JacksonUtils;
import com.fasterxml.jackson.databind.JsonNode;

import java.util.HashMap
import java.util.Map

import function uk.gov.hmcts.reform.orgrolemapping.domain.service.RequestMappingService.logMsg;


/*
 * 1: HRS admin "HRS Team Leader" role mapping.
 */
rule "hrs_team_leader_role"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.HRS_1_0.getValue())
    $cap: CaseWorkerAccessProfile(hasValidJobTitle(JobTitle.HRS_TEAM_LEADER),
                                  hasValidServiceCode(Jurisdiction.HRS),
                                  !suspended)
then
    Map<String,JsonNode> attribute = new HashMap<>();
    attribute.put(Attributes.Name.JURISDICTION, JacksonUtils.convertObjectIntoJsonNode(Jurisdiction.HRS.getName()));
    attribute.put(Attributes.Name.PRIMARY_LOCATION, JacksonUtils.convertObjectIntoJsonNode($cap.getPrimaryLocationId()));

    insert(
        RoleAssignment.builder()
            .actorIdType(ActorIdType.IDAM)
            .actorId($cap.getId())
            .roleCategory(RoleCategory.ADMIN)
            .roleType(RoleType.ORGANISATION)
            .roleName(RoleName.HRS_TEAM_LEADER)
            .grantType(GrantType.STANDARD)
            .classification(Classification.PUBLIC)
            .readOnly(false)
            .attributes(attribute)
            .build()
    );

    logMsg("Rule : hrs_team_leader_role");
end;

/*
 * 2: HRS admin "HRS Sharer" role mapping.
 */
rule "hrs_sharer_role"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.HRS_1_0.getValue())
    $cap: CaseWorkerAccessProfile(hasValidJobTitle(JobTitle.HRS_TEAM_LEADER),
                                  hasValidServiceCode(Jurisdiction.HRS),
                                  !suspended)
then
    Map<String,JsonNode> attribute = new HashMap<>();
    attribute.put(Attributes.Name.JURISDICTION, JacksonUtils.convertObjectIntoJsonNode(Jurisdiction.HRS.getName()));
    attribute.put(Attributes.Name.PRIMARY_LOCATION, JacksonUtils.convertObjectIntoJsonNode($cap.getPrimaryLocationId()));

    insert(
        RoleAssignment.builder()
            .actorIdType(ActorIdType.IDAM)
            .actorId($cap.getId())
            .roleCategory(RoleCategory.ADMIN)
            .roleType(RoleType.ORGANISATION)
            .roleName(RoleName.HRS_SHARER)
            .grantType(GrantType.STANDARD)
            .classification(Classification.PUBLIC)
            .readOnly(false)
            .attributes(attribute)
            .build()
    );

    logMsg("Rule : hrs_sharer_role");
end;

/*
 * 3: HRS admin "HRS Listener" role mapping.
 */
rule "hrs_listener_role"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.HRS_1_0.getValue())
    $cap: CaseWorkerAccessProfile(hasValidJobTitle(JobTitle.HRS_TEAM_LEADER),
                                  hasValidServiceCode(Jurisdiction.HRS),
                                  !suspended)
then
    Map<String,JsonNode> attribute = new HashMap<>();
    attribute.put(Attributes.Name.JURISDICTION, JacksonUtils.convertObjectIntoJsonNode(Jurisdiction.HRS.getName()));
    attribute.put(Attributes.Name.PRIMARY_LOCATION, JacksonUtils.convertObjectIntoJsonNode($cap.getPrimaryLocationId()));

    insert(
        RoleAssignment.builder()
            .actorIdType(ActorIdType.IDAM)
            .actorId($cap.getId())
            .roleCategory(RoleCategory.ADMIN)
            .roleType(RoleType.ORGANISATION)
            .roleName(RoleName.HRS_LISTENER)
            .grantType(GrantType.STANDARD)
            .classification(Classification.PUBLIC)
            .readOnly(false)
            .attributes(attribute)
            .build()
    );

    logMsg("Rule : hrs_listener_role");
end;
