package validationrules.publiclaw;

import uk.gov.hmcts.reform.orgrolemapping.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.ActorIdType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.Classification;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.JudicialAccessProfile;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.JudicialOfficeHolder;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.Authorisation;
import java.util.ArrayList;
import java.util.Arrays;
import java.lang.String;
import  uk.gov.hmcts.reform.orgrolemapping.util.JacksonUtils;
import java.util.HashMap
import java.util.Map
import com.fasterxml.jackson.databind.JsonNode;
import java.time.ZonedDateTime;
import java.time.LocalDateTime;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.FeatureFlag;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.FeatureFlagEnum;
import function uk.gov.hmcts.reform.orgrolemapping.domain.service.RequestMappingService.logMsg;
import function uk.gov.hmcts.reform.orgrolemapping.domain.service.RequestMappingService.addAndGetTicketCodes;
import function uk.gov.hmcts.reform.orgrolemapping.helper.AssignmentRequestBuilder.validateAuthorisation


/*
 * "Stage 1 mapping from judicial appointments(coming from RD JRD access profiles) to judicial office holder.
 */

/*
 * 1: "PUBLICLAW Circuit Judge - Salaried" business role mapping to JOH.
 */
rule "publiclaw_circuit_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment == "Circuit Judge",
                               appointmentType in ("Salaried", "SPTW"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Circuit Judge - Salaried")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_circuit_judge_salaried_joh");
end;

/*
 * 2: "PUBLICLAW Deputy Circuit Judge - Fee Paid" business role mapping to JOH.
 */
rule "publiclaw_deputy_circuit_judge_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment == "Deputy Circuit Judge",
                               appointmentType in ("Fee Paid"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Deputy Circuit Judge - Fee Paid")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_deputy_circuit_judge_fee_paid_joh");
end;

/*
 * 3. "PUBLICLAW Recorder-Fee-Paid" business role business role mapping to JOH.
 */
rule "publiclaw_recorder_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment == "Recorder",
                               appointmentType == "Fee Paid",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Recorder - Fee Paid")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_recorder_fee_paid_joh");
end;

/*
 * 4: "PUBLICLAW Deputy District Judge - PRFD - Fee Paid" business role mapping to JOH.
 */
rule "publiclaw_deputy_district_judge_prfd_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment == "Deputy District Judge - PRFD",
                               appointmentType in ("Fee Paid"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Deputy District Judge - PRFD - Fee Paid")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_deputy_district_judge_prfd_fee_paid_joh");
end;

/*
 * 5: "PUBLICLAW Deputy District Judge (MC) - Fee Paid" business role mapping to JOH.
 */
rule "publiclaw_deputy_district_judge_mc_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment == "Deputy District Judge (MC)- Fee paid",
                               appointmentType in ("Fee Paid"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Deputy District Judge (MC) - Fee Paid")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_deputy_district_judge_mc_fee_paid_joh");
end;

/*
 * 6: "PUBLICLAW Deputy District Judge (MC) - Sitting in Retirement" business role mapping to JOH.
 */
rule "publiclaw_deputy_district_judge_mc_in_retirement_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment == "Deputy District Judge (MC)- Sitting in Retirement",
                               appointmentType in ("Fee Paid"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Deputy District Judge (MC) - Sitting in Retirement")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_deputy_district_judge_mc_in_retirement_joh");
end;

/*
 * 7: "PUBLICLAW Deputy District Judge - Fee Paid" business role mapping to JOH.
 */
rule "publiclaw_deputy_deputy_district_judge_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment == "Deputy District Judge- Fee-Paid",
                               appointmentType in ("Fee Paid"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Deputy District Judge - Fee Paid")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_deputy_deputy_district_judge_fee_paid_joh");
end;

/*
 * 8: "PUBLICLAW Deputy District Judge - Sitting in Retirement - Fee Paid" business role mapping to JOH.
 */
rule "publiclaw_deputy_district_judge_in_retirement_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment == "Deputy District Judge- Sitting in Retirement",
                               appointmentType in ("Fee Paid"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Deputy District Judge - Sitting in Retirement - Fee Paid")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_deputy_district_judge_in_retirement_joh");
end;

/*
 * 9: "PUBLICLAW Deputy High Court Judge - Fee Paid" business role mapping to JOH.
 */
rule "publiclaw_deputy_high_court_judge_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment == "Deputy High Court Judge",
                               appointmentType in ("Fee Paid"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Deputy High Court Judge - Fee Paid")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_deputy_high_court_judge_fee_paid_joh");
end;

/*
 * 10: "PUBLICLAW District Judge - Salaried" business role mapping to JOH.
 */
rule "publiclaw_district_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment == "District Judge",
                               appointmentType in ("Salaried", "SPTW"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW District Judge - Salaried")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_district_judge_salaried_joh");
end;

/*
 * 11: "PUBLICLAW District Judge (MC) - Salaried" business role mapping to JOH.
 */
rule "publiclaw_district_judge_mc_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment == "District Judge (MC)",
                               appointmentType in ("Salaried", "SPTW"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW District Judge (MC) - Salaried")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_district_judge_mc_salaried_joh");
end;

/*
 * 12: "PUBLICLAW High Court Judge - Salaried" business role mapping to JOH.
 * Made obsolete in DTSAM-616 - disabled by PUBLICLAW_WA_1_5 flag.
 * To be removed in DTSAM-568.
 */
rule "publiclaw_high_court_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_0.getValue())
   $f2: FeatureFlag(status == false && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_5.getValue())
   $jap: JudicialAccessProfile(appointment == "High Court Judge",
                               appointmentType in ("Salaried"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW High Court Judge - Salaried")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_high_court_judge_salaried_joh");
end;

/*
 * 12: "PUBLICLAW High Court Judge - Salaried" business role mapping to JOH.
 */
rule "v1_5_publiclaw_high_court_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_5.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "High Court Judge",
                               appointmentType in ("Salaried", "SPTW"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW High Court Judge - Salaried")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : v1_5_publiclaw_high_court_judge_salaried_joh");
end;

/*
 * 13: "PUBLICLAW High Court Judge - Sitting in Retirement - Fee Paid" business role mapping to JOH.
 */
rule "publiclaw_high_court_judge_in_retirement_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment == "High Court Judge- Sitting in Retirement",
                               appointmentType in ("Fee Paid"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW High Court Judge - Sitting in Retirement - Fee Paid")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_high_court_judge_in_retirement_joh");
end;

/*
 * 14: "PUBLICLAW Designated Family Judge - Salaried" business role mapping to JOH.
 * Made obsolete in DTSAM-464 - disabled by PUBLICLAW_WA_1_5 flag.
 * To be removed in DTSAM-568.
 */
rule "publiclaw_designated_family_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_0.getValue())
   $f2: FeatureFlag(status == false && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_5.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (roles != null && roles.contains("Designated Family Judge")),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Designated Family Judge - Salaried")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_designated_family_judge_salaried_joh");
end;

/*
 * 14: "PUBLICLAW Designated Family Judge - Salaried" business role mapping to JOH.
 */
rule "v1_5_publiclaw_designated_family_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_5.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointmentType in ("Salaried", "SPTW"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (roles != null && roles.contains("Designated Family Judge")),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Designated Family Judge - Salaried")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : v1_5_publiclaw_designated_family_judge_salaried_joh");
end;

/*
 * 15: "PUBLICLAW Magistrate - Voluntary" business role mapping to JOH.
 */
rule "publiclaw_magistrate_voluntary_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment == "Magistrate",
                               appointmentType in ("Voluntary"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Magistrate - Voluntary")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_magistrate_voluntary_joh");
end;

/*
 * 16: "PUBLICLAW Tribunal Judge - Salaried" business role mapping to JOH.
 * Made obsolete in DTSAM-616 - disabled by PUBLICLAW_WA_1_5 flag.
 * To be removed in DTSAM-568.
 */
rule "publiclaw_tribunal_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_1.getValue())
   $f2: FeatureFlag(status == false && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_5.getValue())
   $jap: JudicialAccessProfile(appointment == "Tribunal Judge",
                               appointmentType in ("Salaried"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Tribunal Judge - Salaried")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_tribunal_judge_salaried_joh");
end;

/*
 * 16: "PUBLICLAW Tribunal Judge - Salaried" business role mapping to JOH.
 */
rule "v1_5_publiclaw_tribunal_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_5.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Tribunal Judge",
                               appointmentType in ("Salaried", "SPTW"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Tribunal Judge - Salaried")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : v1_5_publiclaw_tribunal_judge_salaried_joh");
end;

/*
 * 17: "PUBLICLAW Employment Judge - Salaried" business role mapping to JOH.
 * Made obsolete in DTSAM-616 - disabled by PUBLICLAW_WA_1_5 flag.
 * To be removed in DTSAM-568.
 */
rule "publiclaw_employment_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_1.getValue())
   $f2: FeatureFlag(status == false && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_5.getValue())
   $jap: JudicialAccessProfile(appointment == "Employment Judge",
                               appointmentType in ("Salaried"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Employment Judge - Salaried")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_employment_judge_salaried_joh");
end;

/*
 * 17: "PUBLICLAW Employment Judge - Salaried" business role mapping to JOH.
 */
rule "v1_5_publiclaw_employment_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_5.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Employment Judge",
                               appointmentType in ("Salaried", "SPTW"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Employment Judge - Salaried")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : v1_5_publiclaw_employment_judge_salaried_joh");
end;

/*
 * 18: "PUBLICLAW Specialist Circuit Judge - Salaried" business role mapping to JOH.
 * Made obsolete in DTSAM-616 - disabled by PUBLICLAW_WA_1_5 flag.
 * To be removed in DTSAM-568.
 */
rule "publiclaw_specialist_circuit_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_1.getValue())
   $f2: FeatureFlag(status == false && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_5.getValue())
   $jap: JudicialAccessProfile(appointment == "Specialist Circuit Judge",
                               appointmentType in ("Salaried"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Specialist Circuit Judge - Salaried")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_specialist_circuit_judge_salaried_joh");
end;

/*
 * 18: "PUBLICLAW Specialist Circuit Judge - Salaried" business role mapping to JOH.
 */
rule "v1_5_publiclaw_specialist_circuit_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_5.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Specialist Circuit Judge",
                               appointmentType in ("Salaried", "SPTW"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Specialist Circuit Judge - Salaried")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : v1_5_publiclaw_specialist_circuit_judge_salaried_joh");
end;

/*
 * 19: "PUBLICLAW Senior Circuit Judge - Salaried" business role mapping to JOH.
 * Made obsolete in DTSAM-616 - disabled by PUBLICLAW_WA_1_5 flag.
 * To be removed in DTSAM-568.
 */
rule "publiclaw_senior_circuit_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_1.getValue())
   $f2: FeatureFlag(status == false && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_5.getValue())
   $jap: JudicialAccessProfile(appointment == "Senior Circuit Judge",
                               appointmentType in ("Salaried"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Senior Circuit Judge - Salaried")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_senior_circuit_judge_salaried_joh");
end;

/*
 * 19: "PUBLICLAW Senior Circuit Judge - Salaried" business role mapping to JOH.
 */
rule "v1_5_publiclaw_senior_circuit_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_5.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Senior Circuit Judge",
                               appointmentType in ("Salaried", "SPTW"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Senior Circuit Judge - Salaried")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : v1_5_publiclaw_senior_circuit_judge_salaried_joh");
end;

/*
 * 20: "PUBLICLAW Circuit Judge - Sitting in Retirement - Fee Paid" business role mapping to JOH.
 */
rule "publiclaw_circuit_judge_in_retirement_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_1.getValue())
   $jap: JudicialAccessProfile(appointment == "Circuit Judge (sitting in retirement)",
                               appointmentType in ("Fee Paid"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Circuit Judge - Sitting in Retirement - Fee Paid")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_circuit_judge_in_retirement_fee_paid_joh");
end;

/*
 * 21: "PUBLICLAW Recorder - Sitting in Retirement - Fee Paid" business role mapping to JOH.
 */
rule "publiclaw_recorder_in_retirement_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_1.getValue())
   $jap: JudicialAccessProfile(appointment == "Recorder (sitting in retirement)",
                               appointmentType in ("Fee Paid"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Recorder - Sitting in Retirement - Fee Paid")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_recorder_in_retirement_fee_paid_joh");
end;

/*
 * 22: "PUBLICLAW Deputy Upper Tribunal Judge - Fee Paid" business role mapping to JOH.
 */
rule "publiclaw_deputy_upper_tribunal_judge_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_1.getValue())
   $jap: JudicialAccessProfile(appointment == "Deputy Upper Tribunal Judge",
                               appointmentType in ("Fee Paid"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW Deputy Upper Tribunal Judge - Fee Paid")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_recorder_in_retirement_fee_paid_joh");
end;

/*
 * 23: "PUBLICLAW District Judge (MC) - Sitting in Retirement - Fee Paid" business role mapping to JOH.
 */
rule "publiclaw_district_judge_mc_in_retirement_fee_paid_joh_v1_3"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_3.getValue())
   $jap: JudicialAccessProfile(appointment == "District Judge (MC) (sitting in retirement)",
                               appointmentType in ("Fee Paid"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW District Judge (MC) - Sitting in Retirement - Fee Paid")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_district_judge_mc_in_retirement_fee_paid_joh_v1_3");
end;

/*
 * 24: "PUBLICLAW District Judge - Sitting in Retirement - Fee Paid" business role mapping to JOH.
 */
rule "publiclaw_district_judge_in_retirement_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PUBLICLAW_WA_1_1.getValue())
   $jap: JudicialAccessProfile(appointment == "District Judge (sitting in retirement)",
                               appointmentType in ("Fee Paid"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               validateAuthorisation(authorisations, "ABA3"))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("PUBLICLAW District Judge - Sitting in Retirement - Fee Paid")
      .jurisdiction("PUBLICLAW")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : publiclaw_district_judge_in_retirement_fee_paid_joh");
end;