package validationrules.stcic;

import uk.gov.hmcts.reform.orgrolemapping.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.ActorIdType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.Classification;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.JudicialAccessProfile;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.JudicialOfficeHolder;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.Authorisation;
import java.util.ArrayList;
import java.util.Arrays;
import java.lang.String;
import  uk.gov.hmcts.reform.orgrolemapping.util.JacksonUtils;
import java.util.HashMap
import java.util.Map
import com.fasterxml.jackson.databind.JsonNode;
import java.time.ZonedDateTime;
import java.time.LocalDateTime;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.FeatureFlag;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.FeatureFlagEnum;
import function uk.gov.hmcts.reform.orgrolemapping.domain.service.RequestMappingService.logMsg;
import function uk.gov.hmcts.reform.orgrolemapping.domain.service.RequestMappingService.addAndGetTicketCodes;
import function uk.gov.hmcts.reform.orgrolemapping.helper.AssignmentRequestBuilder.validateAuthorisation

/*
 * 1: "ST_CIC President of Tribunal-Salaried" business role mapping to JOH.
 */

rule "st_cic_president_of_tribunal_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "President of Tribunal",
                               appointmentType in ("Salaried", "SPTW"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC President of Tribunal-Salaried")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_president_of_tribunal_salaried_joh");
end;

/*
 * 2: "ST_CIC Principal Judge-Salaried" business role mapping to JOH.
 */

rule "st_cic_principal_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Principal Judge",
                               appointmentType in ("Salaried", "SPTW"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC Principal Judge-Salaried")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_principal_judge_salaried_joh");
end;

/*
 * 3: "ST_CIC Tribunal Judge-Fee Paid" business role mapping to JOH.
 */
rule "st_cic_tribunal_judge_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Tribunal Judge",
                               appointmentType == "Fee Paid",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC Tribunal Judge-Fee Paid")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_tribunal_judge_fee_paid_joh");
end;

/*
 * 4: "ST_CIC Tribunal Judge-Salaried" business role mapping to JOH.
 */
rule "st_cic_tribunal_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Tribunal Judge",
                               appointmentType in ("Salaried", "SPTW"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC Tribunal Judge-Salaried")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_tribunal_judge_salaried_joh");
end;

/*
 * 5: "ST_CIC Tribunal Member-Fee Paid" business role mapping to JOH.
 */
rule "st_cic_tribunal_member_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Tribunal Member",
                               appointmentType == "Fee Paid",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC Tribunal Member-Fee Paid")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_tribunal_member_fee_paid_joh");
end;

/*
 * 6: "ST_CIC Tribunal Member Lay-Fee Paid" business role mapping to JOH.
 */
rule "st_cic_tribunal_member_lay_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Tribunal Member Lay",
                               appointmentType == "Fee Paid",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC Tribunal Member Lay-Fee Paid")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_tribunal_member_lay_fee_paid_joh");
end;

/*
 * 7: "ST_CIC Tribunal Member Medical-Salaried" business role mapping to JOH.
 */
rule "st_cic_tribunal_member_medical_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Tribunal Member Medical",
                               appointmentType in ("Salaried", "SPTW"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC Tribunal Member Medical-Salaried")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_tribunal_member_medical_salaried_joh");
end;

/*
 * 8: "ST_CIC Tribunal Member Medical-Fee Paid" business role mapping to JOH.
 */
rule "st_cic_tribunal_member_medical_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Tribunal Member Medical",
                               appointmentType == "Fee Paid",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC Tribunal Member Medical-Fee Paid")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_tribunal_member_medical_fee_paid_joh");
end;

/*
 * 9: "ST_CIC Tribunal Member Disability-Fee Paid" business role mapping to JOH.
 */
rule "st_cic_tribunal_member_disability_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Tribunal Member Disability",
                               appointmentType == "Fee Paid",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC Tribunal Member Disability-Fee Paid")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_tribunal_member_disability_fee_paid_joh");
end;

/*
 * 10: "ST_CIC Tribunal Member Financially Qualified-Fee Paid" business role mapping to JOH.
 */
rule "st_cic_tribunal_member_financially_qualified_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Tribunal Member Financially Qualified",
                               appointmentType == "Fee Paid",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC Tribunal Member Financially Qualified-Fee Paid")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_tribunal_member_financially_qualified_fee_paid_joh");
end;

/*
 * 11: "ST_CIC Tribunal Member Optometrist-Fee Paid" business role mapping to JOH.
 */
rule "st_cic_tribunal_member_optometrist_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Tribunal Member Optometrist",
                               appointmentType == "Fee Paid",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC Tribunal Member Optometrist-Fee Paid")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_tribunal_member_optometrist_fee_paid_joh");
end;

/*
 * 12: "ST_CIC Advisory Committee Member - Magistrate-Fee Paid" business role mapping to JOH.
 */
rule "st_cic_advisory_committee_member_magistrate_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Advisory Committee Member - Magistrate",
                               appointmentType == "Fee Paid",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC Advisory Committee Member - Magistrate-Fee Paid")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_advisory_committee_member_magistrate_fee_paid_joh");
end;

/*
 * 13: "ST_CIC Deputy Upper Tribunal Judge-Fee Paid" business role mapping to JOH.
 */
rule "st_cic_deputy_upper_tribunal_judge_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Deputy Upper Tribunal Judge",
                               appointmentType == "Fee Paid",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC Deputy Upper Tribunal Judge-Fee Paid")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_deputy_upper_tribunal_judge_fee_paid_joh");
end;

/*
 * 14: "ST_CIC Chairman-Fee Paid" business role mapping to JOH.
 */
rule "st_cic_chairman_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Chairman",
                               appointmentType == "Fee Paid",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC Chairman-Fee Paid")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_chairman_fee_paid_joh");
end;

/*
 * 15: "ST_CIC Judge of the First-tier Tribunal (sitting in retirement)-Fee Paid" business role mapping to JOH.
 */
rule "st_cic_judge_of_the_first_tier_tribunal_sitting_in_retirement_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Judge of the First-tier Tribunal (sitting in retirement)",
                               appointmentType == "Fee Paid",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC Judge of the First-tier Tribunal (sitting in retirement)-Fee Paid")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_judge_of_the_first_tier_tribunal_sitting_in_retirement_fee_paid_joh");
end;

/*
 * 16: "ST_CIC Member of the First-tier Tribunal (sitting in retirement)-Fee Paid" business role mapping to JOH.
 */
rule "st_cic_member_of_the_first_tier_tribunal_sitting_in_retirement_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Member of the First-tier Tribunal (sitting in retirement)",
                               appointmentType == "Fee Paid",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC Member of the First-tier Tribunal (sitting in retirement)-Fee Paid")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_member_of_the_first_tier_tribunal_sitting_in_retirement_fee_paid_joh");
end;

/*
 * 17: "ST_CIC Recorder-Fee Paid" business role mapping to JOH.
 */
rule "st_cic_recorder_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Recorder",
                               appointmentType == "Fee Paid",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC Recorder-Fee Paid")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_recorder_fee_paid_joh");
end;

/*
 * 18: "ST_CIC Circuit Judge-Salaried" business role mapping to JOH.
 */
rule "st_cic_circuit_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Circuit Judge",
                               appointmentType in ("Salaried", "SPTW"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC Circuit Judge-Salaried")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_circuit_judge_salaried_joh");
end;

/*
 * 19: "ST_CIC Judge of the First-tier Tribunal-Salaried" business role mapping to JOH.
 */
rule "st_cic_judge_of_the_first_tier_tribunal_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Judge of the First-tier Tribunal",
                               appointmentType in ("Salaried", "SPTW"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC Judge of the First-tier Tribunal-Salaried")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_judge_of_the_first_tier_tribunal_salaried_joh");
end;

/*
 * 20: "ST_CIC Regional Tribunal Judge-Salaried" business role mapping to JOH.
 */
rule "st_cic_regional_tribunal_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Regional Tribunal Judge",
                               appointmentType in ("Salaried", "SPTW"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC Regional Tribunal Judge-Salaried")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_regional_tribunal_judge_salaried_joh");
end;

/*
 * 21: "ST_CIC Magistrate-Fee Paid" business role mapping to JOH.
 */
rule "st_cic_magistrate_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.ST_CIC_WA_1_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Magistrate",
                               appointmentType == "Fee Paid",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BBA2") ))
then
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("ST_CIC Magistrate-Fee Paid")
      .jurisdiction("ST_CIC")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId($jap.getRegionId())
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : st_cic_magistrate_fee_paid_joh");
end;
