version: '3'

services:
  am-org-role-mapping-service:
    build:
      context: .
    image: hmcts/am-org-role-mapping-service
    container_name: am-org-role-mapping-service
    environment:
      - AM_ORG_ROLE_MAPPING_SERVICE_SECRET
      - AM_ORG_ROLE_MAPPING_IDAM_KEY
      - AM_ORG_ROLE_MAPPING_TOKEN_SECRET
      - AM_ORG_ROLE_MAPPING_S2S_AUTHORISED_SERVICES=ccd_gw,am_org_role_mapping_service,am_role_assignment_service
      - IDAM_USER_URL
      - IDAM_S2S_URL
      - ORM_IDAM_CLIENT_ID=am_docker
      - ORG_ROLE_MAPPING_IDAM_CLIENT_SECRET= am_docker_secret
      - ORG_ROLE_MAPPING_IDAM_ADMIN_USERID=orm.admin@hmcts.NET
      - ORG_ROLE_MAPPING_IDAM_ADMIN_PASSWORD=Pa55word11
      - CASE_WORKER_REF_APP_URL=http://localhost:4099
      - JUDICIAL_REF_APP_URL=http://localhost:8091
      - ROLE_ASSIGNMENT_APP_URL=http://localhost:4096
      - ORG_ROLE_MAPPING_IDAM_ADMIN_SCOPE=openid profile roles authorities
      - AZURE_APPLICATIONINSIGHTS_INSTRUMENTATIONKEY
      - REFORM_SERVICE_NAME=am-org-role-mapping-service
      - REFORM_TEAM=am
      - REFORM_ENVIRONMENT=local
      - ORG_ROLE_MAPPING_DB_HOST:am-org-role-mapping-database
      - ORG_ROLE_MAPPING_DB_NAME:org_role_mapping
      - ORG_ROLE_MAPPING_DB_PORT:5432
      - ORG_ROLE_MAPPING_DB_USERNAME:am
      - ORG_ROLE_MAPPING_DB_PASSWORD:am
    ports:
      - ${SERVER_PORT:-4098}:${SERVER_PORT:-4098}
    networks:
      - am-network
    depends_on:
      - am-org-role-mapping-database
    links:
      - am-org-role-mapping-database

  am-org-role-mapping-database:
    build:
      context: docker/database
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - ORG_ROLE_MAPPING_DB_USERNAME=am
      - ORG_ROLE_MAPPING_DB_PASSWORD=am
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5452:5432
    networks:
      - am-network
    volumes:
      - am-org-role-mapping-database-data:/var/lib/postgresql/am-org-role-mapping/data
volumes:
  am-org-role-mapping-database-data:

networks:
  am-network:
    external: true