package validationrules
import uk.gov.hmcts.reform.orgrolemapping.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.Classification;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.UserAccessProfile;
import uk.gov.hmcts.reform.orgrolemapping.util.JacksonUtils;

rule "R01_user_profile_with_roleId_1" salience 100
 when

                     UserAccessProfile(roleId == "1",serviceCode == "BFA1")
  $roleAssignment:   RoleAssignment(roleCategory == RoleCategory.STAFF,roleType == RoleType.ORGANISATION,
                     classification == Classification.PUBLIC,grantType == GrantType.STANDARD)


 then
       System.out.println("R01_user_profile_with_roleId_1");
       $roleAssignment.setRoleName("senior-tribunal-caseworker");
       $roleAssignment.getAttributes().put("jurisdiction",JacksonUtils.convertObjectIntoJsonNode("IA"));
       update($roleAssignment)
 end;


rule "R02_user_profile_with_roleId_2" salience 100
  when

                      UserAccessProfile(roleId == "2",serviceCode == "BFA1")
   $roleAssignment:   RoleAssignment(roleCategory == RoleCategory.STAFF,roleType == RoleType.ORGANISATION,
                      classification == Classification.PUBLIC,grantType == GrantType.STANDARD)


  then
        System.out.println("R02_user_profile_with_roleId_2");
        $roleAssignment.setRoleName("tribunal-caseworker");
        $roleAssignment.getAttributes().put("jurisdiction",JacksonUtils.convertObjectIntoJsonNode("IA"));
        update($roleAssignment)
  end;


