package validationrules.fr;

import com.fasterxml.jackson.databind.JsonNode;
import java.util.HashMap
import java.util.Map
import uk.gov.hmcts.reform.orgrolemapping.domain.model.CaseWorkerAccessProfile;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.constants.RoleAssignmentConstants.Attributes;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.constants.RoleAssignmentConstants.RoleName;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.ActorIdType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.Classification;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.crd.JobTitle;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.FeatureFlagEnum;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.Jurisdiction;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.WorkType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.FeatureFlag;
import uk.gov.hmcts.reform.orgrolemapping.util.JacksonUtils;

import function uk.gov.hmcts.reform.orgrolemapping.domain.service.RequestMappingService.logMsg;

/*
 * DIVORCE admin "hmcts-admin" Org role mapping.
 */
rule "divorce_hmcts_admin_v1"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.FR_WA_1_0.getValue())
    $cap: CaseWorkerAccessProfile(hasValidJobTitle(JobTitle.HEARING_CENTRE_TEAM_LEADER,
                                                   JobTitle.HEARING_CENTRE_ADMIN,
                                                   JobTitle.NBC_TEAM_LEADER,
                                                   JobTitle.NBC_ADMIN),
                                  hasValidServiceCode(Jurisdiction.DIVORCE),
                                  !suspended)
then
    Map<String,JsonNode> attribute = new HashMap<>();
    insert(
        RoleAssignment.builder()
            .actorIdType(ActorIdType.IDAM)
            .actorId($cap.getId())
            .roleCategory(RoleCategory.ADMIN)
            .roleType(RoleType.ORGANISATION)
            .roleName(RoleName.HMCTS_ADMIN)
            .grantType(GrantType.BASIC)
            .classification(Classification.PRIVATE)
            .readOnly(true)
            .attributes(attribute)
            .build());
    logMsg("Rule : divorce_hmcts_admin_v1");
end;

/*
 * DIVORCE admin "hearing-centre-admin" Org role mapping.
 */
rule "divorce_hearing_centre_admin_v1"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.FR_WA_1_0.getValue())
    $cap: CaseWorkerAccessProfile(hasValidJobTitle(JobTitle.HEARING_CENTRE_TEAM_LEADER,
                                                   JobTitle.HEARING_CENTRE_ADMIN),
                                  hasValidServiceCode(Jurisdiction.DIVORCE),
                                  !suspended)
then
    Map<String,JsonNode> attribute = new HashMap<>();
    attribute.put(Attributes.Name.JURISDICTION, JacksonUtils.convertObjectIntoJsonNode(Jurisdiction.DIVORCE.getName()));
    attribute.put(Attributes.Name.PRIMARY_LOCATION, JacksonUtils.convertObjectIntoJsonNode($cap.getPrimaryLocationId()));
    attribute.put(Attributes.Name.REGION, JacksonUtils.convertObjectIntoJsonNode($cap.getRegionId()));
    attribute.put(Attributes.Name.WORK_TYPES, JacksonUtils.convertObjectIntoJsonNode(WorkType.joinValues(
            WorkType.ROUTINE_WORK,
            WorkType.REVIEW_CASE)));
    insert(
        RoleAssignment.builder()
            .actorIdType(ActorIdType.IDAM)
            .actorId($cap.getId())
            .roleCategory(RoleCategory.ADMIN)
            .roleType(RoleType.ORGANISATION)
            .roleName(RoleName.HEARING_CENTRE_ADMIN)
            .grantType(GrantType.STANDARD)
            .classification(Classification.PUBLIC)
            .readOnly(false)
            .attributes(attribute)
            .authorisations($cap.getSkillCodes())
            .build());
    logMsg("Rule : divorce_hearing_centre_admin_v1");
end;

/*
 * DIVORCE admin "hearing-centre-team-leader" Org role mapping.
 */
rule "divorce_hearing_centre_team_leader_v1"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.FR_WA_1_0.getValue())
    $cap: CaseWorkerAccessProfile(hasValidJobTitle(JobTitle.HEARING_CENTRE_TEAM_LEADER),
                                  hasValidServiceCode(Jurisdiction.DIVORCE),
                                  !suspended)
then
    Map<String,JsonNode> attribute = new HashMap<>();
    attribute.put(Attributes.Name.JURISDICTION, JacksonUtils.convertObjectIntoJsonNode(Jurisdiction.DIVORCE.getName()));
    attribute.put(Attributes.Name.PRIMARY_LOCATION, JacksonUtils.convertObjectIntoJsonNode($cap.getPrimaryLocationId()));
    attribute.put(Attributes.Name.REGION, JacksonUtils.convertObjectIntoJsonNode($cap.getRegionId()));
    attribute.put(Attributes.Name.WORK_TYPES, JacksonUtils.convertObjectIntoJsonNode(WorkType.joinValues(
            WorkType.ROUTINE_WORK,
            WorkType.REVIEW_CASE)));
    insert(
        RoleAssignment.builder()
            .actorIdType(ActorIdType.IDAM)
            .actorId($cap.getId())
            .roleCategory(RoleCategory.ADMIN)
            .roleType(RoleType.ORGANISATION)
            .roleName(RoleName.HEARING_CENTRE_TEAM_LEADER)
            .grantType(GrantType.STANDARD)
            .classification(Classification.PUBLIC)
            .readOnly(false)
            .attributes(attribute)
            .authorisations($cap.getSkillCodes())
            .build());
    logMsg("Rule : divorce_hearing_centre_team_leader_v1");
end;

/*
 * DIVORCE admin "national-business-centre" Org role mapping.
 */
rule "divorce_national_business_centre_v1"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.FR_WA_1_0.getValue())
    $cap: CaseWorkerAccessProfile(hasValidJobTitle(JobTitle.NBC_TEAM_LEADER,
                                                   JobTitle.NBC_ADMIN),
                                  hasValidServiceCode(Jurisdiction.DIVORCE),
                                  !suspended)
then
    Map<String,JsonNode> attribute = new HashMap<>();
    attribute.put(Attributes.Name.JURISDICTION, JacksonUtils.convertObjectIntoJsonNode(Jurisdiction.DIVORCE.getName()));
    attribute.put(Attributes.Name.PRIMARY_LOCATION, JacksonUtils.convertObjectIntoJsonNode($cap.getPrimaryLocationId()));
    insert(
        RoleAssignment.builder()
            .actorIdType(ActorIdType.IDAM)
            .actorId($cap.getId())
            .roleCategory(RoleCategory.ADMIN)
            .roleType(RoleType.ORGANISATION)
            .roleName(RoleName.NBC)
            .grantType(GrantType.STANDARD)
            .classification(Classification.PUBLIC)
            .readOnly(false)
            .attributes(attribute)
            .authorisations($cap.getSkillCodes())
            .build());
    logMsg("Rule : divorce_national_business_centre_v1");
end;

/*
 * DIVORCE admin "nbc-team-leader" Org role mapping.
 */
rule "divorce_nbc_team_leader_v1"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.FR_WA_1_0.getValue())
    $cap: CaseWorkerAccessProfile(hasValidJobTitle(JobTitle.NBC_TEAM_LEADER),
                                  hasValidServiceCode(Jurisdiction.DIVORCE),
                                  !suspended)
then
    Map<String,JsonNode> attribute = new HashMap<>();
    attribute.put(Attributes.Name.JURISDICTION, JacksonUtils.convertObjectIntoJsonNode(Jurisdiction.DIVORCE.getName()));
    attribute.put(Attributes.Name.PRIMARY_LOCATION, JacksonUtils.convertObjectIntoJsonNode($cap.getPrimaryLocationId()));
    insert(
        RoleAssignment.builder()
            .actorIdType(ActorIdType.IDAM)
            .actorId($cap.getId())
            .roleCategory(RoleCategory.ADMIN)
            .roleType(RoleType.ORGANISATION)
            .roleName(RoleName.NBC_TEAM_LEADER)
            .grantType(GrantType.STANDARD)
            .classification(Classification.PUBLIC)
            .readOnly(false)
            .attributes(attribute)
            .authorisations($cap.getSkillCodes())
            .build());
    logMsg("Rule : divorce_nbc_team_leader_v1");
end;

/*
 * DIVORCE admin "task-supervisor" Org role mapping.
 */
rule "divorce_admin_task_supervisor_v1"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.FR_WA_1_0.getValue())
    $cap: CaseWorkerAccessProfile(hasValidJobTitle(JobTitle.HEARING_CENTRE_TEAM_LEADER,
                                                   JobTitle.HEARING_CENTRE_ADMIN,
                                                   JobTitle.NBC_TEAM_LEADER,
                                                   JobTitle.NBC_ADMIN),
                                  hasValidServiceCode(Jurisdiction.DIVORCE),
                                  isTaskSupervisor(),
                                  !suspended)
then
    Map<String,JsonNode> attribute = new HashMap<>();
    attribute.put(Attributes.Name.JURISDICTION, JacksonUtils.convertObjectIntoJsonNode(Jurisdiction.DIVORCE.getName()));
    attribute.put(Attributes.Name.PRIMARY_LOCATION, JacksonUtils.convertObjectIntoJsonNode($cap.getPrimaryLocationId()));
    insert(
        RoleAssignment.builder()
            .actorIdType(ActorIdType.IDAM)
            .actorId($cap.getId())
            .roleCategory(RoleCategory.ADMIN)
            .roleType(RoleType.ORGANISATION)
            .roleName(RoleName.TASK_SUPERVISOR)
            .grantType(GrantType.STANDARD)
            .classification(Classification.PUBLIC)
            .readOnly(false)
            .attributes(attribute)
            .authorisations($cap.getSkillCodes())
            .build());
    logMsg("Rule : divorce_admin_task_supervisor_v1");
end;

/*
 * DIVORCE admin "case-allocator" Org role mapping.
 */
rule "divorce_admin_case_allocator_v1"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.FR_WA_1_0.getValue())
    $cap: CaseWorkerAccessProfile(hasValidJobTitle(JobTitle.HEARING_CENTRE_TEAM_LEADER,
                                                   JobTitle.HEARING_CENTRE_ADMIN,
                                                   JobTitle.NBC_TEAM_LEADER,
                                                   JobTitle.NBC_ADMIN),
                                  hasValidServiceCode(Jurisdiction.DIVORCE),
                                  isCaseAllocator(),
                                  !suspended)
then
    Map<String,JsonNode> attribute = new HashMap<>();
    attribute.put(Attributes.Name.JURISDICTION, JacksonUtils.convertObjectIntoJsonNode(Jurisdiction.DIVORCE.getName()));
    attribute.put(Attributes.Name.PRIMARY_LOCATION, JacksonUtils.convertObjectIntoJsonNode($cap.getPrimaryLocationId()));
    insert(
        RoleAssignment.builder()
            .actorIdType(ActorIdType.IDAM)
            .actorId($cap.getId())
            .roleCategory(RoleCategory.ADMIN)
            .roleType(RoleType.ORGANISATION)
            .roleName(RoleName.CASE_ALLOCATOR)
            .grantType(GrantType.STANDARD)
            .classification(Classification.PUBLIC)
            .readOnly(false)
            .attributes(attribute)
            .authorisations($cap.getSkillCodes())
            .build());
    logMsg("Rule : divorce_admin_case_allocator_v1");
end;

/*
 * DIVORCE admin "specific-access-approver-admin" Org role mapping.
 */
rule "divorce_admin_specific_access_approver_admin_v1"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.FR_WA_1_0.getValue())
    $cap: CaseWorkerAccessProfile(hasValidJobTitle(JobTitle.HEARING_CENTRE_TEAM_LEADER,
                                                   JobTitle.NBC_TEAM_LEADER),
                                  hasValidServiceCode(Jurisdiction.DIVORCE),
                                  !suspended)
then
    Map<String,JsonNode> attribute = new HashMap<>();
    attribute.put(Attributes.Name.JURISDICTION, JacksonUtils.convertObjectIntoJsonNode(Jurisdiction.DIVORCE.getName()));
    attribute.put(Attributes.Name.PRIMARY_LOCATION, JacksonUtils.convertObjectIntoJsonNode($cap.getPrimaryLocationId()));
    attribute.put(Attributes.Name.WORK_TYPES, JacksonUtils.convertObjectIntoJsonNode(WorkType.ACCESS_REQUESTS.getValue()));
    insert(
        RoleAssignment.builder()
            .actorIdType(ActorIdType.IDAM)
            .actorId($cap.getId())
            .roleCategory(RoleCategory.ADMIN)
            .roleType(RoleType.ORGANISATION)
            .roleName(RoleName.SPECIFIC_ACCESS_APPROVER_ADMIN)
            .grantType(GrantType.STANDARD)
            .classification(Classification.PUBLIC)
            .readOnly(false)
            .attributes(attribute)
            .authorisations($cap.getSkillCodes())
            .build());
    logMsg("Rule : divorce_admin_specific_access_approver_admin_v1");
end;

/*
 * DIVORCE admin "specific-access-approver-legal-ops" Org role mapping.
 */
rule "divorce_admin_specific_access_approver_legal_ops_v1"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.FR_WA_1_0.getValue())
    $cap: CaseWorkerAccessProfile(hasValidJobTitle(JobTitle.HEARING_CENTRE_TEAM_LEADER),
                                  hasValidServiceCode(Jurisdiction.DIVORCE),
                                  !suspended)
then
    Map<String,JsonNode> attribute = new HashMap<>();
    attribute.put(Attributes.Name.JURISDICTION, JacksonUtils.convertObjectIntoJsonNode(Jurisdiction.DIVORCE.getName()));
    attribute.put(Attributes.Name.PRIMARY_LOCATION, JacksonUtils.convertObjectIntoJsonNode($cap.getPrimaryLocationId()));
    attribute.put(Attributes.Name.WORK_TYPES, JacksonUtils.convertObjectIntoJsonNode(WorkType.ACCESS_REQUESTS.getValue()));
    insert(
        RoleAssignment.builder()
            .actorIdType(ActorIdType.IDAM)
            .actorId($cap.getId())
            .roleCategory(RoleCategory.ADMIN)
            .roleType(RoleType.ORGANISATION)
            .roleName(RoleName.SPECIFIC_ACCESS_APPROVER_LEGAL_OPS)
            .grantType(GrantType.STANDARD)
            .classification(Classification.PUBLIC)
            .readOnly(false)
            .attributes(attribute)
            .authorisations($cap.getSkillCodes())
            .build());
    logMsg("Rule : divorce_admin_specific_access_approver_legal_ops_v1");
end;
