package validationrules.fr;

import uk.gov.hmcts.reform.orgrolemapping.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.constants.JudicialOfficeHolder.Office;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.ActorIdType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.Classification;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.jrd.AdditionalRole;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.jrd.Appointment;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.jrd.AppointmentGroup;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.Jurisdiction;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.JudicialAccessProfile;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.JudicialOfficeHolder;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.Authorisation;

import java.util.ArrayList;
import java.util.Arrays;
import java.lang.String;
import  uk.gov.hmcts.reform.orgrolemapping.util.JacksonUtils;
import java.util.HashMap
import java.util.Map
import com.fasterxml.jackson.databind.JsonNode;
import java.time.ZonedDateTime;
import java.time.LocalDateTime;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.FeatureFlag;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.FeatureFlagEnum;
import function uk.gov.hmcts.reform.orgrolemapping.domain.service.RequestMappingService.logMsg;
import function uk.gov.hmcts.reform.orgrolemapping.domain.service.RequestMappingService.addAndGetTicketCodes;
import function uk.gov.hmcts.reform.orgrolemapping.helper.AssignmentRequestBuilder.validateAuthorisation

/*
 * Rule 1 "Generic Fee Paid" business role mapping to JOH.
 */
rule "v1_0_fr_judge_fee_paid_joh"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.FR_WA_1_0.getValue())
    $jap: JudicialAccessProfile(isFeePaid(),
                                hasValidEndDate(),
                                hasValidAuthorisation(Jurisdiction.DIVORCE))
then

    insert(
        JudicialOfficeHolder.builder()
            .userId($jap.getUserId())
            .office(Office.FR.FR_JUDGE_FEE_PAID)
            .jurisdiction(Jurisdiction.DIVORCE.getName())
            .ticketCodes($jap.getTicketCodes())
            .beginTime($jap.getBeginTime())
            .endTime($jap.getEndTime())
            .regionId($jap.getRegionId())
            .baseLocationId($jap.getBaseLocationId())
            .primaryLocation($jap.getPrimaryLocationId())
            .contractType($jap.getAppointmentType())
            .build()
    );

    logMsg("Rule : v1_0_fr_judge_fee_paid_joh");
end;

/*
 * Rule 2 "Generic Salaried" business role mapping to JOH.
 */
rule "v1_0_fr_judge_salaried_joh"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.FR_WA_1_0.getValue())
    $jap: JudicialAccessProfile(isSalaried(),
                                hasValidEndDate(),
                                hasValidAuthorisation(Jurisdiction.DIVORCE))
then

    insert(
        JudicialOfficeHolder.builder()
            .userId($jap.getUserId())
            .office(Office.FR.FR_JUDGE_SALARIED)
            .jurisdiction(Jurisdiction.DIVORCE.getName())
            .ticketCodes($jap.getTicketCodes())
            .beginTime($jap.getBeginTime())
            .endTime($jap.getEndTime())
            .regionId($jap.getRegionId())
            .baseLocationId($jap.getBaseLocationId())
            .primaryLocation($jap.getPrimaryLocationId())
            .contractType($jap.getAppointmentType())
            .build()
    );

    logMsg("Rule : v1_0_fr_judge_salaried_joh");
end;

/*
 * Rule 3 "Generic Leadership Judge" business role mapping to JOH.
 */
rule "v1_0_fr_leadership_judge_salaried_joh"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.FR_WA_1_0.getValue())
    $jap: JudicialAccessProfile(hasAppointmentCode(Appointment.CIRCUIT_JUDGE)
                                        || hasAppointmentCode(Appointment.HIGH_COURT_JUDGE),
                                isSalaried(),
                                hasValidEndDate(),
                                hasValidAuthorisation(Jurisdiction.DIVORCE))
then

    insert(
        JudicialOfficeHolder.builder()
            .userId($jap.getUserId())
            .office(Office.FR.FR_LEADERSHIP_JUDGE_SALARIED)
            .jurisdiction(Jurisdiction.DIVORCE.getName())
            .ticketCodes($jap.getTicketCodes())
            .beginTime($jap.getBeginTime())
            .endTime($jap.getEndTime())
            .regionId($jap.getRegionId())
            .baseLocationId($jap.getBaseLocationId())
            .primaryLocation($jap.getPrimaryLocationId())
            .contractType($jap.getAppointmentType())
            .build()
    );

    logMsg("Rule : v1_0_fr_leadership_judge_salaried_joh");
end;

