package validationrules.employment;

import uk.gov.hmcts.reform.orgrolemapping.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.constants.JudicialOfficeHolder.Office;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.ActorIdType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.Classification;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.jrd.AdditionalRole;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.jrd.Appointment;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.jrd.AppointmentGroup;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.Jurisdiction;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.JudicialAccessProfile;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.JudicialOfficeHolder;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.Authorisation;

import java.util.ArrayList;
import java.util.Arrays;
import java.lang.String;
import  uk.gov.hmcts.reform.orgrolemapping.util.JacksonUtils;
import java.util.HashMap
import java.util.Map
import com.fasterxml.jackson.databind.JsonNode;
import java.time.ZonedDateTime;
import java.time.LocalDateTime;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.FeatureFlag;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.FeatureFlagEnum;
import function uk.gov.hmcts.reform.orgrolemapping.domain.service.RequestMappingService.logMsg;
import function uk.gov.hmcts.reform.orgrolemapping.domain.service.RequestMappingService.addAndGetTicketCodes;
import function uk.gov.hmcts.reform.orgrolemapping.helper.AssignmentRequestBuilder.validateAuthorisation


/*
 * "EMPLOYMENT President of Tribunal" business role mapping to JOH.
 * Made obsolete in DTSAM-995 - rule will be disabled when EMPLOYMENT_WA_3_0 is enabled.
 * To be removed in DTSAM-1041.
 */
rule "employment_president_of_tribunal_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_0.getValue())
   $f2: FeatureFlag(flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_2.getValue())
   $f3: FeatureFlag(status == false && flagName == FeatureFlagEnum.EMPLOYMENT_WA_3_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "President of Tribunal",
                               appointmentType == "Salaried",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BHA1") ))
then
  String regionId = null;
  if ($f2.isStatus()){
  // Solution to work around issue with Scottish judges with region 12 not being
  // able to see Scottish cases set up with region 11.
     regionId = "12".equals($jap.getRegionId()) ? "11" : $jap.getRegionId();
  } else {
     regionId = $jap.getRegionId();
  }
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("EMPLOYMENT President of Tribunal-Salaried")
      .jurisdiction("EMPLOYMENT")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId(regionId)
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : employment_president_of_tribunal_salaried_joh");
end;

/*
 * "EMPLOYMENT President of Tribunal" business role mapping to JOH for v3_0.
 */
rule "v3_0_employment_president_of_tribunal_salaried_joh"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_3_0.getValue())
    $jap: JudicialAccessProfile(hasAppointmentCode(Appointment.PRESIDENT_OF_TRIBUNAL),
                                isSalaried(),
                                hasValidEndDate(),
                                hasValidAuthorisation(Jurisdiction.EMPLOYMENT))
then
    // Solution to work around issue with Scottish judges with region 12 not being
    // able to see Scottish cases set up with region 11.
    String regionId = "12".equals($jap.getRegionId()) ? "11" : $jap.getRegionId();

   insert(
        JudicialOfficeHolder.builder()
            .userId($jap.getUserId())
            .office(Office.Employment.PRESIDENT_OF_TRIBUNAL_SALARIED)
            .jurisdiction(Jurisdiction.EMPLOYMENT.getName())
            .ticketCodes($jap.getTicketCodes())
            .beginTime($jap.getBeginTime())
            .endTime($jap.getEndTime())
            .regionId(regionId)
            .baseLocationId($jap.getBaseLocationId())
            .primaryLocation($jap.getPrimaryLocationId())
            .contractType($jap.getAppointmentType())
            .build()
    );

    logMsg("Rule : v3_0_employment_president_of_tribunal_salaried_joh");
end;

/*
 * "EMPLOYMENT President, Employment Tribunals (Scotland)" business role mapping to JOH.
 * Made obsolete in DTSAM-995 - rule will be disabled when EMPLOYMENT_WA_3_0 is enabled.
 * To be removed in DTSAM-1041.
 */
rule "employment_president_employment_tribunals_scotland_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_1.getValue())
   $f2: FeatureFlag(flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_2.getValue())
   $f3: FeatureFlag(status == false && flagName == FeatureFlagEnum.EMPLOYMENT_WA_3_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "President, Employment Tribunals (Scotland)",
                               appointmentType == "Salaried",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BHA1") ))
then
  String regionId = null;
  if ($f2.isStatus()){
    // Solution to work around issue with Scottish judges with region 12 not being
    // able to see Scottish cases set up with region 11.
     regionId = "12".equals($jap.getRegionId()) ? "11" : $jap.getRegionId();
  } else {
     regionId = $jap.getRegionId();
  }
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("EMPLOYMENT President Employment Tribunals (Scotland)-Salaried")
      .jurisdiction("EMPLOYMENT")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId(regionId)
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : employment_president_employment_tribunals_scotland_salaried_joh");
end;

/*
 * "EMPLOYMENT President, Employment Tribunals (Scotland)" business role mapping to JOH for v3_0.
 */
rule "v3_0_employment_president_employment_tribunals_scotland_salaried_joh"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_3_0.getValue())
    $jap: JudicialAccessProfile(hasAppointmentCode(Appointment.PRESIDENT_ET_SCOTLAND),
                                isSalaried(),
                                hasValidEndDate(),
                                hasValidAuthorisation(Jurisdiction.EMPLOYMENT))
then
    // Solution to work around issue with Scottish judges with region 12 not being
    // able to see Scottish cases set up with region 11.
    String regionId = "12".equals($jap.getRegionId()) ? "11" : $jap.getRegionId();

    insert(
        JudicialOfficeHolder.builder()
            .userId($jap.getUserId())
            .office(Office.Employment.PRESIDENT_ET_SCOTLAND_SALARIED)
            .jurisdiction(Jurisdiction.EMPLOYMENT.getName())
            .ticketCodes($jap.getTicketCodes())
            .beginTime($jap.getBeginTime())
            .endTime($jap.getEndTime())
            .regionId(regionId)
            .baseLocationId($jap.getBaseLocationId())
            .primaryLocation($jap.getPrimaryLocationId())
            .contractType($jap.getAppointmentType())
            .build()
    );

    logMsg("Rule : v3_0_employment_president_employment_tribunals_scotland_salaried_joh");
end;

/*
 * "EMPLOYMENT Vice-President, Employment Tribunal (Scotland)" business role mapping to JOH.
 * Made obsolete in DTSAM-995 - rule will be disabled when EMPLOYMENT_WA_3_0 is enabled.
 * To be removed in DTSAM-1041.
 */
rule "employment_vice_president_employment_tribunal_scotland_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_3.getValue())
   $f2: FeatureFlag(status == false && flagName == FeatureFlagEnum.EMPLOYMENT_WA_3_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Vice-President, Employment Tribunal (Scotland)",
                               appointmentType == "Salaried",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BHA1") ))
then
  // Solution to work around issue with Scottish judges with region 12 not being
  // able to see Scottish cases set up with region 11.
  String regionId = "12".equals($jap.getRegionId()) ? "11" : $jap.getRegionId();
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("EMPLOYMENT Vice-President Employment Tribunal (Scotland)-Salaried")
      .jurisdiction("EMPLOYMENT")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId(regionId)
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : employment_vice_president_employment_tribunal_scotland_salaried_joh");
end;

/*
 * "EMPLOYMENT Vice President" business role mapping to JOH.
 * Made obsolete in DTSAM-995 - rule will be disabled when EMPLOYMENT_WA_3_0 is enabled.
 * To be removed in DTSAM-1041.
 */
rule "employment_vice_president_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_0.getValue())
   $f2: FeatureFlag(flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_2.getValue())
   $f3: FeatureFlag(status == false && flagName == FeatureFlagEnum.EMPLOYMENT_WA_3_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Vice President",
                               appointmentType == "Salaried",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BHA1") ))
then
  String regionId = null;
  if ($f2.isStatus()){
    // Solution to work around issue with Scottish judges with region 12 not being
    // able to see Scottish cases set up with region 11.
     regionId = "12".equals($jap.getRegionId()) ? "11" : $jap.getRegionId();
  } else {
     regionId = $jap.getRegionId();
  }
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("EMPLOYMENT Vice President-Salaried")
      .jurisdiction("EMPLOYMENT")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId(regionId)
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : employment_vice_president_salaried_joh");
end;

/*
 * "EMPLOYMENT Vice President" business role mapping to JOH for v3_0.
 */
rule "v3_0_employment_vice_president_salaried_joh"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_3_0.getValue())
    $jap: JudicialAccessProfile(hasAppointmentCode(Appointment.VICE_PRESIDENT)
                                    || hasAppointmentCode(Appointment.VICE_PRESIDENT_ET_SCOTLAND),
                                isSalaried(),
                                hasValidEndDate(),
                                hasValidAuthorisation(Jurisdiction.EMPLOYMENT))
then
    // Solution to work around issue with Scottish judges with region 12 not being
    // able to see Scottish cases set up with region 11.
    String regionId = "12".equals($jap.getRegionId()) ? "11" : $jap.getRegionId();

    insert(
        JudicialOfficeHolder.builder()
            .userId($jap.getUserId())
            .office(Office.Employment.VICE_PRESIDENT_SALARIED)
            .jurisdiction(Jurisdiction.EMPLOYMENT.getName())
            .ticketCodes($jap.getTicketCodes())
            .beginTime($jap.getBeginTime())
            .endTime($jap.getEndTime())
            .regionId(regionId)
            .baseLocationId($jap.getBaseLocationId())
            .primaryLocation($jap.getPrimaryLocationId())
            .contractType($jap.getAppointmentType())
            .build()
    );

    logMsg("Rule : v3_0_employment_vice_president_salaried_joh");
end;

/*
 * "EMPLOYMENT Regional Employment Judge" business role mapping to JOH.
 * Made obsolete in DTSAM-995 - rule will be disabled when EMPLOYMENT_WA_3_0 is enabled.
 * To be removed in DTSAM-1041.
 */
rule "employment_regional_employment_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_0.getValue())
   $f2: FeatureFlag(flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_2.getValue())
   $f3: FeatureFlag(status == false && flagName == FeatureFlagEnum.EMPLOYMENT_WA_3_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Regional Employment Judge",
                               appointmentType == "Salaried",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BHA1") ))
then
  String regionId = null;
  if ($f2.isStatus()){
    // Solution to work around issue with Scottish judges with region 12 not being
    // able to see Scottish cases set up with region 11.
     regionId = "12".equals($jap.getRegionId()) ? "11" : $jap.getRegionId();
  } else {
     regionId = $jap.getRegionId();
  }
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("EMPLOYMENT Regional Employment Judge-Salaried")
      .jurisdiction("EMPLOYMENT")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId(regionId)
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : employment_regional_employment_judge_salaried_joh");
end;

/*
 * "EMPLOYMENT Regional Employment Judge" business role mapping to JOH for v3_0.
 */
rule "v3_0_employment_regional_employment_judge_salaried_joh"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_3_0.getValue())
    $jap: JudicialAccessProfile(hasAppointmentCode(Appointment.REGIONAL_EMPLOYMENT_JUDGE),
                                isSalaried(),
                                hasValidEndDate(),
                                hasValidAuthorisation(Jurisdiction.EMPLOYMENT))
then
    // Solution to work around issue with Scottish judges with region 12 not being
    // able to see Scottish cases set up with region 11.
    String regionId = "12".equals($jap.getRegionId()) ? "11" : $jap.getRegionId();

    insert(
        JudicialOfficeHolder.builder()
            .userId($jap.getUserId())
            .office(Office.Employment.REGIONAL_EMPLOYMENT_JUDGE_SALARIED)
            .jurisdiction(Jurisdiction.EMPLOYMENT.getName())
            .ticketCodes($jap.getTicketCodes())
            .beginTime($jap.getBeginTime())
            .endTime($jap.getEndTime())
            .regionId(regionId)
            .baseLocationId($jap.getBaseLocationId())
            .primaryLocation($jap.getPrimaryLocationId())
            .contractType($jap.getAppointmentType())
            .build()
    );

    logMsg("Rule : v3_0_employment_regional_employment_judge_salaried_joh");
end;

/*
 * "EMPLOYMENT Employment Judge" business role mapping to JOH.
 * Made obsolete in DTSAM-989 - rule will be disabled when EMPLOYMENT_WA_3_0 is enabled.
 * To be removed in DTSAM-1041.
 */
rule "employment_employment_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_0.getValue())
   $f2: FeatureFlag(flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_2.getValue())
   $f3: FeatureFlag(status == false && flagName == FeatureFlagEnum.EMPLOYMENT_WA_3_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Employment Judge",
                               appointmentType in ("Salaried", "SPTW"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BHA1") ))
then
  String regionId = null;
  if ($f2.isStatus()){
    // Solution to work around issue with Scottish judges with region 12 not being
    // able to see Scottish cases set up with region 11.
     regionId = "12".equals($jap.getRegionId()) ? "11" : $jap.getRegionId();
  } else {
     regionId = $jap.getRegionId();
  }
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("EMPLOYMENT Employment Judge-Salaried")
      .jurisdiction("EMPLOYMENT")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId(regionId)
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : employment_employment_judge_salaried_joh");
end;

/*
 * "EMPLOYMENT Employment Judge" business role mapping to JOH for v3_0.
 */
rule "v3_0_employment_employment_judge_salaried_joh"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_3_0.getValue())
    $jap: JudicialAccessProfile(!hasAppointmentCode(Appointment.PRESIDENT_OF_TRIBUNAL),
                                isSalaried(),
                                hasValidEndDate(),
                                hasValidAuthorisation(Jurisdiction.EMPLOYMENT))
then
    // Solution to work around issue with Scottish judges with region 12 not being
    // able to see Scottish cases set up with region 11.
    String regionId = "12".equals($jap.getRegionId()) ? "11" : $jap.getRegionId();

    insert(
        JudicialOfficeHolder.builder()
            .userId($jap.getUserId())
            .office(Office.Employment.EMPLOYMENT_JUDGE_SALARIED)
            .jurisdiction(Jurisdiction.EMPLOYMENT.getName())
            .ticketCodes($jap.getTicketCodes())
            .beginTime($jap.getBeginTime())
            .endTime($jap.getEndTime())
            .regionId(regionId)
            .baseLocationId($jap.getBaseLocationId())
            .primaryLocation($jap.getPrimaryLocationId())
            .contractType($jap.getAppointmentType())
            .build()
    );

    logMsg("Rule : v3_0_employment_employment_judge_salaried_joh");
end;

/*
 * "EMPLOYMENT Employment Judge" business role mapping to JOH.
 * Made obsolete in DTSAM-988 - rule will be disabled when EMPLOYMENT_WA_3_0 is enabled.
 * To be removed in DTSAM-1041.
 */
rule "v1_5_employment_employment_judge_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_5.getValue())
   $f2: FeatureFlag(status == false && flagName == FeatureFlagEnum.EMPLOYMENT_WA_3_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment in ("Employment Judge",
                                            "Employment Judge (Sitting in Retirement)",
                                            "Employment Judge (sitting in retirement)",
                                            "Recorder",
                                            "Regional Tribunal Judge",
                                            "Tribunal Judge"
                                            ),
                               appointmentType == "Fee Paid",
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BHA1") ))
then
  // Solution to work around issue with Scottish judges with region 12 not being
  // able to see Scottish cases set up with region 11.
  String regionId = "12".equals($jap.getRegionId()) ? "11" : $jap.getRegionId();
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("EMPLOYMENT Employment Judge-Fee-Paid")
      .jurisdiction("EMPLOYMENT")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId(regionId)
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : v1_5_employment_employment_judge_fee_paid_joh");
end;

/*
 * "EMPLOYMENT Employment Judge" business role mapping to JOH for v3_0.
 */
rule "v3_0_employment_employment_judge_fee_paid_joh"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_3_0.getValue())
    $jap: JudicialAccessProfile(!hasAppointmentCode(AppointmentGroup.ANY_TRIBUNAL_MEMBER),
                                isFeePaid(),
                                hasValidEndDate(),
                                hasValidAuthorisation(Jurisdiction.EMPLOYMENT))
then
    // Solution to work around issue with Scottish judges with region 12 not being
    // able to see Scottish cases set up with region 11.
    String regionId = "12".equals($jap.getRegionId()) ? "11" : $jap.getRegionId();

   insert(
        JudicialOfficeHolder.builder()
            .userId($jap.getUserId())
            .office(Office.Employment.EMPLOYMENT_JUDGE_FEE_PAID)
            .jurisdiction(Jurisdiction.EMPLOYMENT.getName())
            .ticketCodes($jap.getTicketCodes())
            .beginTime($jap.getBeginTime())
            .endTime($jap.getEndTime())
            .regionId(regionId)
            .baseLocationId($jap.getBaseLocationId())
            .primaryLocation($jap.getPrimaryLocationId())
            .contractType($jap.getAppointmentType())
            .build()
    );

    logMsg("Rule : v3_0_employment_employment_judge_fee_paid_joh");
end;


/*
 * "EMPLOYMENT Tribunal Member" business role mapping to JOH.
 * Made obsolete in DTSAM-994 - rule will be disabled when EMPLOYMENT_WA_3_0 is enabled.
 * To be removed in DTSAM-1041.
 */
rule "employment_tribunal_member_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_0.getValue())
   $f2: FeatureFlag(flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_2.getValue())
   $f3: FeatureFlag(status == false && flagName == FeatureFlagEnum.EMPLOYMENT_WA_3_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Tribunal Member",
                               appointmentType == "Fee Paid",
                               baseLocationId in ("1036","1037"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BHA1") ))
then
  String regionId = null;
  if ($f2.isStatus()){
    // Solution to work around issue with Scottish judges with region 12 not being
    // able to see Scottish cases set up with region 11.
     regionId = "12".equals($jap.getRegionId()) ? "11" : $jap.getRegionId();
  } else {
     regionId = $jap.getRegionId();
  }
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("EMPLOYMENT Tribunal Member-Fee-Paid")
      .jurisdiction("EMPLOYMENT")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId(regionId)
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : employment_tribunal_member_fee_paid_joh");
end;

/*
 * "EMPLOYMENT Tribunal Member" business role mapping to JOH for v3_0.
 */
rule "v3_0_employment_tribunal_member_fee_paid_joh"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_3_0.getValue())
    $jap: JudicialAccessProfile(hasAppointmentCode(Appointment.TRIBUNAL_MEMBER)
                                    || hasAppointmentCode(Appointment.TRIBUNAL_MEMBER_LAY),
                                isFeePaid(),
                                hasValidEndDate(),
                                hasValidAuthorisation(Jurisdiction.EMPLOYMENT))
then
    // Solution to work around issue with Scottish judges with region 12 not being
    // able to see Scottish cases set up with region 11.
    String regionId = "12".equals($jap.getRegionId()) ? "11" : $jap.getRegionId();

    insert(
        JudicialOfficeHolder.builder()
            .userId($jap.getUserId())
            .office(Office.Employment.TRIBUNAL_MEMBER_FEE_PAID)
            .jurisdiction(Jurisdiction.EMPLOYMENT.getName())
            .ticketCodes($jap.getTicketCodes())
            .beginTime($jap.getBeginTime())
            .endTime($jap.getEndTime())
            .regionId(regionId)
            .baseLocationId($jap.getBaseLocationId())
            .primaryLocation($jap.getPrimaryLocationId())
            .contractType($jap.getAppointmentType())
            .build()
    );

    logMsg("Rule : v3_0_employment_tribunal_member_fee_paid_joh");
end;

/*
 * "EMPLOYMENT Tribunal Member Lay" business role mapping to JOH.
 * Made obsolete in DTSAM-994 - rule will be disabled when EMPLOYMENT_WA_3_0 is enabled.
 * To be removed in DTSAM-1041.
 */
rule "employment_tribunal_member_lay_fee_paid_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_0.getValue())
   $f2: FeatureFlag(flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_2.getValue())
   $f3: FeatureFlag(status == false && flagName == FeatureFlagEnum.EMPLOYMENT_WA_3_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointment == "Tribunal Member Lay",
                               appointmentType == "Fee Paid",
                               baseLocationId in ("1036","1037"),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BHA1") ))
then
  String regionId = null;
  if ($f2.isStatus()){
    // Solution to work around issue with Scottish judges with region 12 not being
    // able to see Scottish cases set up with region 11.
     regionId = "12".equals($jap.getRegionId()) ? "11" : $jap.getRegionId();
  } else {
     regionId = $jap.getRegionId();
  }
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("EMPLOYMENT Tribunal Member Lay-Fee-Paid")
      .jurisdiction("EMPLOYMENT")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId(regionId)
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : employment_tribunal_member_lay_fee_paid_joh");
end;

/*
 * "EMPLOYMENT Acting Regional Employment Judge" business role mapping to JOH.
 * Made obsolete in DTSAM-995 - rule will be disabled when EMPLOYMENT_WA_3_0 is enabled.
 * To be removed in DTSAM-1041.
 */
rule "employment_acting_regional_employment_judge_salaried_joh"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_4.getValue())
   $f3: FeatureFlag(status == false && flagName == FeatureFlagEnum.EMPLOYMENT_WA_3_0.getValue())
   $jap: JudicialAccessProfile(appointment != null,
                               appointmentType in ("Salaried", "SPTW"),
                               (roles != null && roles.contains("Acting Regional Employment Judge")),
                               (endTime == null || endTime.compareTo(ZonedDateTime.now()) >= 0),
                               (validateAuthorisation(authorisations, "BHA1") ))
then
  // Solution to work around issue with Scottish judges with region 12 not being
  // able to see Scottish cases set up with region 11.
  String regionId = "12".equals($jap.getRegionId()) ? "11" : $jap.getRegionId();
  insert(
      JudicialOfficeHolder.builder()
      .userId($jap.getUserId())
      .office("EMPLOYMENT Acting Regional Employment Judge-Salaried")
      .jurisdiction("EMPLOYMENT")
      .ticketCodes($jap.getTicketCodes())
      .beginTime($jap.getBeginTime())
      .endTime($jap.getEndTime())
      .regionId(regionId)
      .baseLocationId($jap.getBaseLocationId())
      .primaryLocation($jap.getPrimaryLocationId())
      .contractType($jap.getAppointmentType())
      .build());
      logMsg("Rule : employment_acting_regional_employment_judge_salaried_joh");
end;

/*
 * "EMPLOYMENT Acting Regional Employment Judge" business role mapping to JOH for v3_0.
 */
rule "v3_0_employment_acting_regional_employment_judge_salaried_joh"
when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_3_0.getValue())
    $jap: JudicialAccessProfile(appointment != null,
                                hasValidAdditionalRole(AdditionalRole.ACTING_REGIONAL_EMPLOYMENT_JUDGE),
                                isSalaried(),
                                hasValidEndDate(),
                                hasValidAuthorisation(Jurisdiction.EMPLOYMENT))
then
    // Solution to work around issue with Scottish judges with region 12 not being
    // able to see Scottish cases set up with region 11.
    String regionId = "12".equals($jap.getRegionId()) ? "11" : $jap.getRegionId();

    insert(
        JudicialOfficeHolder.builder()
            .userId($jap.getUserId())
            .office(Office.Employment.ACTING_REGIONAL_EMPLOYMENT_JUDGE_SALARIED)
            .jurisdiction(Jurisdiction.EMPLOYMENT.getName())
            .ticketCodes($jap.getTicketCodes())
            .beginTime($jap.getBeginTime())
            .endTime($jap.getEndTime())
            .regionId(regionId)
            .baseLocationId($jap.getBaseLocationId())
            .primaryLocation($jap.getPrimaryLocationId())
            .contractType($jap.getAppointmentType())
            .build()
    );

    logMsg("Rule : v3_0_employment_acting_regional_employment_judge_salaried_joh");
end;
