package validationrules.employment;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.ActorIdType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.Classification;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.CaseWorkerAccessProfile;
import java.util.ArrayList;
import  uk.gov.hmcts.reform.orgrolemapping.util.JacksonUtils;
import java.util.HashMap
import java.util.Map
import com.fasterxml.jackson.databind.JsonNode;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.FeatureFlag;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.FeatureFlagEnum;
import function uk.gov.hmcts.reform.orgrolemapping.domain.service.RequestMappingService.logMsg;


/*
 * employment admin "hearing-centre-team-leader" Org role mapping.
 */

rule "employment_admin_hearing_centre_team_leader_org_role"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_0.getValue())
  $cap: CaseWorkerAccessProfile(roleId in ("3"), serviceCode == "BHA1", !suspended)
then
   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode("EMPLOYMENT"));
   attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($cap.getPrimaryLocationId()));
   attribute.put("region", JacksonUtils.convertObjectIntoJsonNode($cap.getRegionId()));

  insert(
      RoleAssignment.builder()
      .actorIdType(ActorIdType.IDAM)
      .actorId($cap.getId())
      .roleCategory(RoleCategory.ADMIN)
      .roleType(RoleType.ORGANISATION)
      .roleName("hearing-centre-team-leader")
      .grantType(GrantType.STANDARD)
      .classification(Classification.PUBLIC)
      .readOnly(false)
      .attributes(attribute)
      .build());
      logMsg("Rule : employment_admin_hearing_centre_team_leader_org_role");
end;

/*
 * employment admin "hearing-centre-admin" Org role mapping.
 */

rule "employment_admin_hearing_centre_admin_org_role"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_0.getValue())
  $cap: CaseWorkerAccessProfile(roleId in("3","4"), serviceCode == "BHA1", !suspended)
then
   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode("EMPLOYMENT"));
   attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($cap.getPrimaryLocationId()));
   attribute.put("workTypes", JacksonUtils.convertObjectIntoJsonNode("hearing_work,routine_work,applications,amendments"));
   attribute.put("region", JacksonUtils.convertObjectIntoJsonNode($cap.getRegionId()));
  insert(
        RoleAssignment.builder()
        .actorIdType(ActorIdType.IDAM)
        .actorId($cap.getId())
        .roleCategory(RoleCategory.ADMIN)
        .roleType(RoleType.ORGANISATION)
        .roleName("hearing-centre-admin")
        .grantType(GrantType.STANDARD)
        .classification(Classification.PUBLIC)
        .readOnly(false)
        .attributes(attribute)
        .build());
        logMsg("Rule : employment_admin_hearing_centre_admin_org_role");
end;

/*
 * employment admin "regional-centre-team-leader" Org role mapping.
 */

rule "employment_admin_regional_centre_team_leader_org_role"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_0.getValue())
  $cap: CaseWorkerAccessProfile(roleId in ("12"), serviceCode == "BHA1", !suspended)
then
   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode("EMPLOYMENT"));
   attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($cap.getPrimaryLocationId()));
   attribute.put("region", JacksonUtils.convertObjectIntoJsonNode($cap.getRegionId()));

  insert(
      RoleAssignment.builder()
      .actorIdType(ActorIdType.IDAM)
      .actorId($cap.getId())
      .roleCategory(RoleCategory.ADMIN)
      .roleType(RoleType.ORGANISATION)
      .roleName("regional-centre-team-leader")
      .grantType(GrantType.STANDARD)
      .classification(Classification.PUBLIC)
      .readOnly(false)
      .attributes(attribute)
      .build());
      logMsg("Rule : employment_admin_regional_centre_team_leader_org_role");
end;

/*
 * employment admin "regional-centre-admin" Org role mapping.
 */

rule "employment_admin_regional_centre_admin_org_role"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_0.getValue())
  $cap: CaseWorkerAccessProfile(roleId in("12","13"), serviceCode == "BHA1", !suspended)
then
   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode("EMPLOYMENT"));
   attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($cap.getPrimaryLocationId()));
   attribute.put("workTypes", JacksonUtils.convertObjectIntoJsonNode("hearing_work,routine_work,applications,amendments"));
   attribute.put("region", JacksonUtils.convertObjectIntoJsonNode($cap.getRegionId()));
  insert(
        RoleAssignment.builder()
        .actorIdType(ActorIdType.IDAM)
        .actorId($cap.getId())
        .roleCategory(RoleCategory.ADMIN)
        .roleType(RoleType.ORGANISATION)
        .roleName("regional-centre-admin")
        .grantType(GrantType.STANDARD)
        .classification(Classification.PUBLIC)
        .readOnly(false)
        .attributes(attribute)
        .build());
        logMsg("Rule : employment_admin_regional_centre_admin_org_role");
end;

/*
 * employment admin "hmcts-admin" Org role mapping.
 */

rule "employment_admin_hmcts_admin_org_role"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_0.getValue())
  $cap: CaseWorkerAccessProfile(roleId in ("3","12","4","13","5"), serviceCode == "BHA1", !suspended)
then
   Map<String,JsonNode> attribute = new HashMap<>();
  insert(
      RoleAssignment.builder()
      .actorIdType(ActorIdType.IDAM)
      .actorId($cap.getId())
      .roleCategory(RoleCategory.ADMIN)
      .roleType(RoleType.ORGANISATION)
      .roleName("hmcts-admin")
      .grantType(GrantType.BASIC)
      .classification(Classification.PRIVATE)
      .readOnly(true)
      .attributes(attribute)
      .build());
      logMsg("Rule : employment_admin_hmcts_admin_org_role");
end;

/*
 * employment admin "task-supervisor" Org role mapping.
 */

rule "employment_admin_task_supervisor_org_role"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_0.getValue())
  $cap: CaseWorkerAccessProfile(roleId in("3","12","4","13","5"), serviceCode == "BHA1", !suspended, taskSupervisorFlag == "Y")
then
   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode("EMPLOYMENT"));
   attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($cap.getPrimaryLocationId()));

  insert(
      RoleAssignment.builder()
      .actorIdType(ActorIdType.IDAM)
      .actorId($cap.getId())
      .roleCategory(RoleCategory.ADMIN)
      .roleType(RoleType.ORGANISATION)
      .roleName("task-supervisor")
      .grantType(GrantType.STANDARD)
      .classification(Classification.PUBLIC)
      .readOnly(false)
      .attributes(attribute)
      .build());
      logMsg("Rule : employment_admin_task_supervisor_org_role");
end;

/*
 * employment admin "case-allocator" Org role mapping.
 */

rule "employment_admin_case_allocator_org_role"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_0.getValue())
  $cap: CaseWorkerAccessProfile(roleId in("3","12","4","13","5"), serviceCode == "BHA1", !suspended, caseAllocatorFlag == "Y")
then
   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode("EMPLOYMENT"));
   attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($cap.getPrimaryLocationId()));

  insert(
      RoleAssignment.builder()
      .actorIdType(ActorIdType.IDAM)
      .actorId($cap.getId())
      .roleCategory(RoleCategory.ADMIN)
      .roleType(RoleType.ORGANISATION)
      .roleName("case-allocator")
      .grantType(GrantType.STANDARD)
      .classification(Classification.PUBLIC)
      .readOnly(false)
      .attributes(attribute)
      .build());
      logMsg("Rule : employment_admin_case_allocator_org_role");
end;

/*
 * employment admin "specific-access-approver-admin" Org role mapping.
 */

rule "employment_admin_specific_access_approver_org_role"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_0.getValue())
  $cap: CaseWorkerAccessProfile(roleId in ("3","12"), serviceCode == "BHA1", !suspended)
then
   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode("EMPLOYMENT"));
   attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($cap.getPrimaryLocationId()));
   attribute.put("region", JacksonUtils.convertObjectIntoJsonNode($cap.getRegionId()));
   attribute.put("workTypes", JacksonUtils.convertObjectIntoJsonNode("access_requests"));
  insert(
      RoleAssignment.builder()
      .actorIdType(ActorIdType.IDAM)
      .actorId($cap.getId())
      .roleCategory(RoleCategory.ADMIN)
      .roleType(RoleType.ORGANISATION)
      .roleName("specific-access-approver-admin")
      .grantType(GrantType.STANDARD)
      .classification(Classification.PUBLIC)
      .readOnly(false)
      .attributes(attribute)
      .build());
      logMsg("Rule : employment_specific_access_approver_admin_org_role");
end;

/*
 * employment admin "clerk" Org role mapping.
 */

rule "employment_admin_clerk_org_role"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.EMPLOYMENT_WA_1_0.getValue())
  $cap: CaseWorkerAccessProfile(roleId =="5", serviceCode == "BHA1", !suspended)
then
   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode("EMPLOYMENT"));
   attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($cap.getPrimaryLocationId()));
   attribute.put("workTypes", JacksonUtils.convertObjectIntoJsonNode("hearing_work,routine_work,applications,amendments"));
   attribute.put("region", JacksonUtils.convertObjectIntoJsonNode($cap.getRegionId()));
  insert(
        RoleAssignment.builder()
        .actorIdType(ActorIdType.IDAM)
        .actorId($cap.getId())
        .roleCategory(RoleCategory.ADMIN)
        .roleType(RoleType.ORGANISATION)
        .roleName("clerk")
        .grantType(GrantType.STANDARD)
        .classification(Classification.PUBLIC)
        .readOnly(false)
        .attributes(attribute)
        .build());
        logMsg("Rule : employment_admin_clerk_org_role");
end;
