spring:
  cache:
    type: none
  security:
    oauth2:
      client:
        provider:
          oidc:
            issuer-uri: http://localhost:${wiremock.server.port:5000}/o

idam:
  s2s-auth:
    totp_secret: ${AM_ORG_ROLE_MAPPING_SERVICE_SECRET:test}
    microservice: am_org_role_mapping_service
    url: http://localhost:${wiremock.server.port:4502}
  api.url: http://localhost:${wiremock.server.port:5000}
  client:
    admin:
      userId: ${ORG_ROLE_MAPPING_IDAM_ADMIN_USERID:}
      secret: ${ORG_ROLE_MAPPING_IDAM_ADMIN_PASSWORD:}
      scope: ${ORG_ROLE_MAPPING_IDAM_ADMIN_SCOPE:openid profile roles authorities view-user}
feign:
  client:
    config:
      crdclient:
        url: http://localhost:${wiremock.server.port:8095}
      roleAssignmentApp:
        url: http://localhost:${wiremock.server.port:4096}
      jrdClient:
        url: http://localhost:${wiremock.server.port:8091}
      jbsClient:
        url: http://localhost:${wiremock.server.port:4097}
      idamClient:
        url: http://localhost:${wiremock.server.port:5000}

amqp:
  crd:
    enabled: false
  jrd:
    enabled: false
