package validationrules.privatelaw;

import uk.gov.hmcts.reform.orgrolemapping.domain.model.constants.RoleAssignmentConstants.Attributes;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.Jurisdiction;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.FeatureFlagEnum;
import function uk.gov.hmcts.reform.orgrolemapping.domain.service.RequestMappingService.logMsg;
import function uk.gov.hmcts.reform.orgrolemapping.helper.AssignmentRequestBuilder.cloneNewRoleAssignmentAndChangeRegion;

/*
 * PRIVATELAW "multi-region" Org role mapping. (JUDICIAL)
 */

rule "privatelaw_multi_region_dependency_org_role__judicial__region_1"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PRIVATELAW_WA_1_9.getValue())
  $ra: RoleAssignment(roleCategory == RoleCategory.JUDICIAL,
                      attributes[Attributes.Name.JURISDICTION] != null && attributes[Attributes.Name.JURISDICTION].asText() in (Jurisdiction.PRIVATELAW.getName()),
                      attributes[Attributes.Name.CONTRACT_TYPE] != null && attributes[Attributes.Name.CONTRACT_TYPE].asText() in (Attributes.ContractType.SALARIED),
                      attributes[Attributes.Name.REGION] != null && attributes[Attributes.Name.REGION].asText() in ("5"))
  not RoleAssignment(actorId == $ra.getActorId(),
                     roleName == $ra.getRoleName(),
                     roleCategory == $ra.getRoleCategory(),
                     attributes[Attributes.Name.JURISDICTION] != null && attributes[Attributes.Name.JURISDICTION].asText() in (Jurisdiction.PRIVATELAW.getName()),
                     attributes[Attributes.Name.CONTRACT_TYPE] != null && attributes[Attributes.Name.CONTRACT_TYPE].asText() in (Attributes.ContractType.SALARIED),
                     attributes[Attributes.Name.REGION] != null && attributes[Attributes.Name.REGION].asText() == "1")
then
   insert(cloneNewRoleAssignmentAndChangeRegion($ra, "1"));
   logMsg("Rule : privatelaw_multi_region_dependency_org_role__judicial__region_1");
end;

rule "privatelaw_multi_region_dependency_org_role__judicial__region_5"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PRIVATELAW_WA_1_9.getValue())
  $ra: RoleAssignment(roleCategory == RoleCategory.JUDICIAL,
                      attributes[Attributes.Name.JURISDICTION] != null && attributes[Attributes.Name.JURISDICTION].asText() in (Jurisdiction.PRIVATELAW.getName()),
                      attributes[Attributes.Name.CONTRACT_TYPE] != null && attributes[Attributes.Name.CONTRACT_TYPE].asText() in (Attributes.ContractType.SALARIED),
                      attributes[Attributes.Name.REGION] != null && attributes[Attributes.Name.REGION].asText() in ("1"))
  not RoleAssignment(actorId == $ra.getActorId(),
                     roleName == $ra.getRoleName(),
                     roleCategory == $ra.getRoleCategory(),
                     attributes[Attributes.Name.JURISDICTION] != null && attributes[Attributes.Name.JURISDICTION].asText() in (Jurisdiction.PRIVATELAW.getName()),
                     attributes[Attributes.Name.CONTRACT_TYPE] != null && attributes[Attributes.Name.CONTRACT_TYPE].asText() in (Attributes.ContractType.SALARIED),
                     attributes[Attributes.Name.REGION] != null && attributes[Attributes.Name.REGION].asText() == "5")
then
   insert(cloneNewRoleAssignmentAndChangeRegion($ra, "5"));
   logMsg("Rule : privatelaw_multi_region_dependency_org_role__judicial__region_5");
end;
