package validationrules.privatelaw;

import uk.gov.hmcts.reform.orgrolemapping.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.FeatureFlagEnum;
import function uk.gov.hmcts.reform.orgrolemapping.domain.service.RequestMappingService.logMsg;
import function uk.gov.hmcts.reform.orgrolemapping.helper.AssignmentRequestBuilder.cloneNewRoleAssignmentAndChangeRegion;

/*
 * PRIVATELAW "multi-region" Org role mapping. (JUDICIAL)
 */

rule "privatelaw_multi_region_dependency_org_role__judicial__region_1"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PRIVATELAW_WA_1_9.getValue())
  $ra: RoleAssignment(roleCategory == RoleCategory.JUDICIAL,
                      hasValidAuthorisation(Jurisdiction.PRIVATELAW),
                      isSalaried(),
                      attributes["region"] != null && attributes["region"].asText() in ("5"))
  not RoleAssignment(actorId == $ra.getActorId(),
                     roleName == $ra.getRoleName(),
                     roleCategory == $ra.getRoleCategory(),
                     hasValidAuthorisation(Jurisdiction.PRIVATELAW),
                     isSalaried(),
                     attributes["region"] != null && attributes["region"].asText() == "1")
then
   insert(cloneNewRoleAssignmentAndChangeRegion($ra, "1"));
   logMsg("Rule : privatelaw_multi_region_dependency_org_role__judicial__region_1");
end;

rule "privatelaw_multi_region_dependency_org_role__judicial__region_5"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.PRIVATELAW_WA_1_9.getValue())
  $ra: RoleAssignment(roleCategory == RoleCategory.JUDICIAL,
                      hasValidAuthorisation(Jurisdiction.PRIVATELAW),
                      isSalaried(),
                      attributes["region"] != null && attributes["region"].asText() in ("1"))
  not RoleAssignment(actorId == $ra.getActorId(),
                     roleName == $ra.getRoleName(),
                     roleCategory == $ra.getRoleCategory(),
                     hasValidAuthorisation(Jurisdiction.PRIVATELAW),
                     isSalaried(),
                     attributes["region"] != null && attributes["region"].asText() == "5")
then
   insert(cloneNewRoleAssignmentAndChangeRegion($ra, "5"));
   logMsg("Rule : privatelaw_multi_region_dependency_org_role__judicial__region_5");
end;
