package validationrules.core;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.JudicialOfficeHolder;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.irm.IdamRole;

/*
 * Query which returns all role assignments currently in working memory.
 */
query getRoleAssignments ()
    $roleAssignment: RoleAssignment()
end;


/*
 * Query which returns all judicial office holders currently in working memory.
 */
query getJudicialOfficeHolders ()
    $judicialOfficeHolder: JudicialOfficeHolder()
end;


/*
 * Query which returns all IDAM Rp;es currently in working memory.
 */
query getIdamRoles ()
    $idamRole: IdamRole()
end;
