package validationrules.core;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.RoleAssignment;

/*
 * Query which returns all role assignments currently in working memory.
 */
query getRoleAssignments ()
    $roleAssignment: RoleAssignment()
end;


/*
 * Query which returns all judicial office holders currently in working memory.
 */
query getJudicialOfficeHolders ()
    $judicialOfficeHolder: JudicialOfficeHolder()
end;
