package validationrules.core;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.ActorIdType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.Classification;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.CaseWorkerAccessProfile;
import  uk.gov.hmcts.reform.orgrolemapping.util.JacksonUtils;
import java.util.HashMap
import java.util.Map
import com.fasterxml.jackson.databind.JsonNode;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.FeatureFlag;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.FeatureFlagEnum;
import function uk.gov.hmcts.reform.orgrolemapping.domain.service.RequestMappingService.logMsg;

/*
 * For on-boarding new service, we just need to include the corresponding service code in every
 * rule as per the hearing role requirements captured on service configuration page.
 */

/*
 * All services "hearing-manager" Org role mapping.
 */
 rule "global_hearing_manager_legal_ops"
 when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.SSCS_HEARING_1_0.getValue())
   $up: CaseWorkerAccessProfile((roleId in ("2","16") && serviceCode in ("BBA3"))
                                  || (roleId in ("1","2") && serviceCode in ("ABA3","ABA5")),
                                  !suspended)
 then
    Map<String,JsonNode> attribute = new HashMap<>();
    attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode(getJurisdictionFromServiceCode($up.getServiceCode())));
    attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($up.getPrimaryLocationId()));

   insert(
       RoleAssignment.builder()
       .actorIdType(ActorIdType.IDAM)
       .actorId($up.getId())
       .roleCategory(RoleCategory.LEGAL_OPERATIONS)
       .roleType(RoleType.ORGANISATION)
       .roleName("hearing-manager")
       .grantType(GrantType.STANDARD)
       .classification(Classification.PUBLIC)
       .readOnly(false)
       .attributes(attribute)
       .build());
       logMsg("Rule : global_hearing_manager_legal_ops");
 end;

 /*
  * All services "hearing-viewer" Org role mapping.
  */
 rule "global_hearing_viewer_legal_ops"
 when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.SSCS_HEARING_1_0.getValue())
   $up: CaseWorkerAccessProfile((roleId in ("2","16") && serviceCode in ("BBA3"))
                                  || (roleId in ("1","2") && serviceCode in ("ABA3","ABA5")),
                                 !suspended)
 then
    Map<String,JsonNode> attribute = new HashMap<>();
    attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode(getJurisdictionFromServiceCode($up.getServiceCode())));
    attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($up.getPrimaryLocationId()));

   insert(
       RoleAssignment.builder()
       .actorIdType(ActorIdType.IDAM)
       .actorId($up.getId())
       .roleCategory(RoleCategory.LEGAL_OPERATIONS)
       .roleType(RoleType.ORGANISATION)
       .roleName("hearing-viewer")
       .grantType(GrantType.STANDARD)
       .classification(Classification.PUBLIC)
       .readOnly(false)
       .attributes(attribute)
       .build());
       logMsg("Rule : global_hearing_viewer_legal_ops");
 end;