package validationrules.core;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.ActorIdType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.Classification;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.CaseWorkerAccessProfile;
import  uk.gov.hmcts.reform.orgrolemapping.util.JacksonUtils;
import java.util.HashMap
import java.util.Map
import com.fasterxml.jackson.databind.JsonNode;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.FeatureFlag;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.FeatureFlagEnum;
import function uk.gov.hmcts.reform.orgrolemapping.domain.service.RequestMappingService.logMsg;

/*
 * For on-boarding new services, we just need to include the office reference of JOH which is defined for
 * hearing role requirements.
 */

 /*
  * All services "hearing-viewer" Org role mapping.
  */

 rule "global_hearing_viewer_judicial"
 when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.SSCS_HEARING_1_0.getValue())
   $joh: JudicialOfficeHolder(office in ("SSCS Judge", "Family Judge",
   "PUBLICLAW District Judge - Salaried", "PUBLICLAW District Judge (MC) - SPTW",
   "PUBLICLAW High Court Judge - Salaried", "PUBLICLAW Circuit Judge - Salaried",
   "PUBLICLAW Deputy District Judge (MC) - Fee Paid", "PUBLICLAW Deputy District Judge (MC) - Sitting in Retirement",
   "PUBLICLAW Deputy District Judge - Fee Paid", "PUBLICLAW Deputy District Judge - Sitting in Retirement - Fee Paid",
   "PUBLICLAW Deputy District Judge - PRFD - Fee Paid", "PUBLICLAW Deputy High Court Judge - Fee Paid",
   "PUBLICLAW High Court Judge - Sitting in Retirement - Fee Paid",
   "PUBLICLAW Magistrate - Voluntary", "PUBLICLAW Designated Family Judge - Salaried",
   "PUBLICLAW Deputy Circuit Judge - Fee Paid", "PUBLICLAW District Judge (MC) - Salaried", "PUBLICLAW Recorder - Fee Paid"))
 then
    Map<String,JsonNode> attribute = new HashMap<>();
    attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode($joh.getJurisdiction()));
    attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($joh.getPrimaryLocation()));
   insert(
       RoleAssignment.builder()
       .actorIdType(ActorIdType.IDAM)
       .actorId($joh.getUserId())
       .roleCategory(RoleCategory.JUDICIAL)
       .roleType(RoleType.ORGANISATION)
       .roleName("hearing-viewer")
       .grantType(GrantType.STANDARD)
       .classification(Classification.PUBLIC)
       .readOnly(false)
       .beginTime($joh.getBeginTime())
       .endTime($joh.getEndTime() !=null ? $joh.getEndTime().plusDays(1):null)
       .attributes(attribute)
       .authorisations($joh.getTicketCodes())
       .build());
       logMsg("Rule : global_hearing_viewer_judicial");
 end;

  rule "global_hearing_manager_judicial"
  when
    $f:  FeatureFlag(status && flagName == FeatureFlagEnum.SSCS_HEARING_1_0.getValue())
    $joh: JudicialOfficeHolder(office in (
    "PUBLICLAW District Judge - Salaried", "PUBLICLAW District Judge (MC) - SPTW",
    "PUBLICLAW High Court Judge - Salaried", "PUBLICLAW Circuit Judge - Salaried",
    "PUBLICLAW Deputy District Judge (MC) - Fee Paid", "PUBLICLAW Deputy District Judge (MC) - Sitting in Retirement",
    "PUBLICLAW Deputy District Judge - Fee Paid", "PUBLICLAW Deputy District Judge - Sitting in Retirement - Fee Paid",
    "PUBLICLAW Deputy District Judge - PRFD - Fee Paid", "PUBLICLAW Deputy High Court Judge - Fee Paid",
    "PUBLICLAW High Court Judge - Sitting in Retirement - Fee Paid",
    "PUBLICLAW Designated Family Judge - Salaried", "PUBLICLAW District Judge (MC) - Salaried",
    "PUBLICLAW Deputy Circuit Judge - Fee Paid","PUBLICLAW Recorder - Fee Paid"))
  then
     Map<String,JsonNode> attribute = new HashMap<>();
     attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode($joh.getJurisdiction()));
     attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($joh.getPrimaryLocation()));
    insert(
        RoleAssignment.builder()
        .actorIdType(ActorIdType.IDAM)
        .actorId($joh.getUserId())
        .roleCategory(RoleCategory.JUDICIAL)
        .roleType(RoleType.ORGANISATION)
        .roleName("hearing-manager")
        .grantType(GrantType.STANDARD)
        .classification(Classification.PUBLIC)
        .readOnly(false)
        .beginTime($joh.getBeginTime())
        .endTime($joh.getEndTime() !=null ? $joh.getEndTime().plusDays(1):null)
        .attributes(attribute)
        .authorisations($joh.getTicketCodes())
        .build());
        logMsg("Rule : global_hearing_viewer_judicial");
  end;