package validationrules.core;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.UserAccessProfile;
import function uk.gov.hmcts.reform.orgrolemapping.domain.service.RequestMappingService.logMsg;

rule "role_assignment"
salience 1000
when
  $ra: RoleAssignment()
then
   logMsg("We have role assignment created for role : " + $ra.getRoleName() + " : " + $ra);
end;

rule "user_access_profile"
salience 1000
when
  $up: UserAccessProfile()
then
   logMsg("We have a user access profile " + $up.getId() + " : " + $up);
end;
