package validationrules.core;

function String getJurisdictionFromServiceCode(String serviceCode) {
    String result = null;
        switch (serviceCode) {
            case "BBA3":
                result = "SSCS";
                break;
            case "AAA6":
            case "AAA7":
                result = "CIVIL";
                break;
            case "ABA5":
                result = "PRIVATELAW";
                break;
        }
        return result;
}