package validationrules.iac;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.RoleAssignment;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.constants.RoleAssignmentConstants.Attributes;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.constants.RoleAssignmentConstants.RoleName;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.ActorIdType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleCategory;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.RoleType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.WorkType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.Classification;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.crd.JobTitle;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.GrantType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.Jurisdiction;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.WorkType;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.CaseWorkerAccessProfile;
import java.util.ArrayList;
import  uk.gov.hmcts.reform.orgrolemapping.util.JacksonUtils;
import java.util.HashMap
import java.util.Map
import com.fasterxml.jackson.databind.JsonNode;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.FeatureFlag;
import uk.gov.hmcts.reform.orgrolemapping.domain.model.enums.FeatureFlagEnum;
import function uk.gov.hmcts.reform.orgrolemapping.domain.service.RequestMappingService.logMsg;

/*
 * Made obsolete in DTSAM-1072 - disabled by iac_wa_1_5 flag.
 * To be removed in DTSAM-1086.
 * IAC ctsc "ctsc" Org role mapping.
 */

rule "iac_ctsc_caseworker_v11"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.IAC_1_1.getValue())
   $f1: FeatureFlag(status == false && flagName == FeatureFlagEnum.IAC_WA_1_5.getValue())
  $up: CaseWorkerAccessProfile(roleId in ("9","10"), serviceCode == "BFA1", !suspended)
then
   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode("IA"));
   attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($up.getPrimaryLocationId()));
   attribute.put("workTypes", JacksonUtils.convertObjectIntoJsonNode("hearing_work, upper_tribunal, routine_work"));
  insert(
      RoleAssignment.builder()
      .actorIdType(ActorIdType.IDAM)
      .actorId($up.getId())
      .roleCategory(RoleCategory.CTSC)
      .roleType(RoleType.ORGANISATION)
      .roleName("ctsc")
      .grantType(GrantType.STANDARD)
      .classification(Classification.PUBLIC)
      .readOnly(false)
      .attributes(attribute)
      .authorisations($up.getSkillCodes())
      .build());
      logMsg("Rule : iac_ctsc_caseworker_v11");
end;

/*
 * IAC ctsc "ctsc" Org role mapping for 1.5 .
 * Made obsolete in DTSAM-1333 - rule will be disabled when iac_wa_1_8 is enabled.
 * To be removed in DTSAM-1338.
 */

rule "v_1_5_iac_ctsc_caseworker"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.IAC_WA_1_5.getValue())
   $f2: FeatureFlag(status == false && flagName == FeatureFlagEnum.IAC_WA_1_8.getValue())
  $up: CaseWorkerAccessProfile(roleId in ("9","10"), serviceCode == "BFA1", !suspended)
then
   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode("IA"));
   attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($up.getPrimaryLocationId()));
   attribute.put("workTypes", JacksonUtils.convertObjectIntoJsonNode("hearing_work, upper_tribunal, routine_work, stf_24w_hearing_work, stf_24w_upper_tribunal, stf_24w_routine_work"));
  insert(
      RoleAssignment.builder()
      .actorIdType(ActorIdType.IDAM)
      .actorId($up.getId())
      .roleCategory(RoleCategory.CTSC)
      .roleType(RoleType.ORGANISATION)
      .roleName("ctsc")
      .grantType(GrantType.STANDARD)
      .classification(Classification.PUBLIC)
      .readOnly(false)
      .attributes(attribute)
      .authorisations($up.getSkillCodes())
      .build());
      logMsg("Rule : v_1_5_iac_ctsc_caseworker");
end;

/*
 * PROBATE ctsc "ctsc" Org role mapping for v1_8.
 */

rule "v1_8_probate_ctsc"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.IAC_WA_1_8.getValue())
  $up: CaseWorkerAccessProfile(hasValidJobTitle(JobTitle.CTSC_TEAM_LEADER, JobTitle.CTSC_ADMIN),
                               hasValidServiceCode(Jurisdiction.IAC), !suspended)
then

   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put(Attributes.Name.JURISDICTION, JacksonUtils.convertObjectIntoJsonNode(Jurisdiction.IAC.getName()));
   attribute.put(Attributes.Name.PRIMARY_LOCATION, JacksonUtils.convertObjectIntoJsonNode($up.getPrimaryLocationId()));
   attribute.put(Attributes.Name.WORK_TYPES,
                 JacksonUtils.convertObjectIntoJsonNode(WorkType.joinValues(
                                                            WorkType.HEARING_WORK,
                                                            WorkType.UPPER_TRIBUNAL,
                                                            WorkType.ROUTINE_WORK,
                                                            WorkType.STF_24W_HEARING_WORK,
                                                            WorkType.STF_24W_UPPER_TRIBUNAL,
                                                            WorkType.STF_24W_ROUTINE_WORK,
                                                            WorkType.QUERIES,
                                                            WorkType.QUERIES_STF)));
  insert(

      RoleAssignment.builder()
        .actorIdType(ActorIdType.IDAM)
        .actorId($up.getId())
        .roleCategory(RoleCategory.CTSC)
        .roleType(RoleType.ORGANISATION)
        .roleName(RoleName.CTSC)
        .grantType(GrantType.STANDARD)
        .classification(Classification.PUBLIC)
        .readOnly(false)
        .attributes(attribute)
        .authorisations($up.getSkillCodes())
        .build());
      logMsg("Rule : v1_8_probate_ctsc");
end;

rule "iac_hmcts_ctsc_caseworker_v11"
when
  $f:  FeatureFlag(status && flagName == FeatureFlagEnum.IAC_1_1.getValue())
  $up: CaseWorkerAccessProfile(roleId in ("9","10"), serviceCode == "BFA1", !suspended)
then
   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($up.getPrimaryLocationId()));
  insert(
      RoleAssignment.builder()
      .actorIdType(ActorIdType.IDAM)
      .actorId($up.getId())
      .roleCategory(RoleCategory.CTSC)
      .roleType(RoleType.ORGANISATION)
      .roleName("hmcts-ctsc")
      .grantType(GrantType.BASIC)
      .classification(Classification.PRIVATE)
      .readOnly(true)
      .attributes(attribute)
      .build());
      logMsg("Rule : iac_hmcts_ctsc_caseworker_v11");
end;

/*
 * IAC ctsc "ctsc-team-leader" Org role mapping. added for CR:AM2732
 * Made obsolete in DTSAM-1072 - disabled by iac_wa_1_5 flag.
 * To be removed in DTSAM-1086.
 */

rule "iac_ctsc_team_leader_v12"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.IAC_WA_1_2.getValue())
   $f1: FeatureFlag(status == false && flagName == FeatureFlagEnum.IAC_WA_1_5.getValue())
  $up: CaseWorkerAccessProfile(roleId in ("9"), serviceCode == "BFA1", !suspended)
then
   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode("IA"));
   attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($up.getPrimaryLocationId()));
   attribute.put("workTypes", JacksonUtils.convertObjectIntoJsonNode("hearing_work, upper_tribunal, routine_work"));
  insert(
      RoleAssignment.builder()
      .actorIdType(ActorIdType.IDAM)
      .actorId($up.getId())
      .roleCategory(RoleCategory.CTSC)
      .roleType(RoleType.ORGANISATION)
      .roleName("ctsc-team-leader")
      .grantType(GrantType.STANDARD)
      .classification(Classification.PUBLIC)
      .readOnly(false)
      .attributes(attribute)
      .authorisations($up.getSkillCodes())
      .build());
      logMsg("Rule : iac_ctsc_team_leader_v12");
end;

/*
 * IAC ctsc "ctsc-team-leader" Org role mapping. added for CR:AM2732 for 1.5.
 */

rule "v_1_5_iac_ctsc_team_leader"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.IAC_WA_1_5.getValue())
  $up: CaseWorkerAccessProfile(roleId in ("9"), serviceCode == "BFA1", !suspended)
then
   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode("IA"));
   attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($up.getPrimaryLocationId()));
   attribute.put("workTypes", JacksonUtils.convertObjectIntoJsonNode("hearing_work, upper_tribunal, routine_work, stf_24w_hearing_work, stf_24w_upper_tribunal, stf_24w_routine_work"));
  insert(
      RoleAssignment.builder()
      .actorIdType(ActorIdType.IDAM)
      .actorId($up.getId())
      .roleCategory(RoleCategory.CTSC)
      .roleType(RoleType.ORGANISATION)
      .roleName("ctsc-team-leader")
      .grantType(GrantType.STANDARD)
      .classification(Classification.PUBLIC)
      .readOnly(false)
      .attributes(attribute)
      .authorisations($up.getSkillCodes())
      .build());
      logMsg("Rule : v_1_5_iac_ctsc_team_leader");
end;

/*
 * IAC ctsc "case-allocator" Org role mapping. added for CR:AM2732
 */

rule "iac_case_allocator_v12"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.IAC_WA_1_2.getValue())
  $up: CaseWorkerAccessProfile(roleId in ("9","10"), serviceCode == "BFA1", !suspended,caseAllocatorFlag == "Y")
then
   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode("IA"));
   attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($up.getPrimaryLocationId()));
  insert(
      RoleAssignment.builder()
      .actorIdType(ActorIdType.IDAM)
      .actorId($up.getId())
      .roleCategory(RoleCategory.CTSC)
      .roleType(RoleType.ORGANISATION)
      .roleName("case-allocator")
      .grantType(GrantType.STANDARD)
      .classification(Classification.PUBLIC)
      .readOnly(false)
      .attributes(attribute)
      .authorisations($up.getSkillCodes())
      .build());
      logMsg("Rule : iac_case_allocator_v12");
end;

/*
 * IAC ctsc "task-supervisor" Org role mapping. added for CR:AM2732
 */

rule "iac_task_supervisor_v12"
when
   $f:  FeatureFlag(status && flagName == FeatureFlagEnum.IAC_WA_1_2.getValue())
  $up: CaseWorkerAccessProfile(roleId in ("9","10"), serviceCode == "BFA1", !suspended,taskSupervisorFlag == "Y")
then
   Map<String,JsonNode> attribute = new HashMap<>();
   attribute.put("jurisdiction", JacksonUtils.convertObjectIntoJsonNode("IA"));
   attribute.put("primaryLocation", JacksonUtils.convertObjectIntoJsonNode($up.getPrimaryLocationId()));
  insert(
      RoleAssignment.builder()
      .actorIdType(ActorIdType.IDAM)
      .actorId($up.getId())
      .roleCategory(RoleCategory.CTSC)
      .roleType(RoleType.ORGANISATION)
      .roleName("task-supervisor")
      .grantType(GrantType.STANDARD)
      .classification(Classification.PUBLIC)
      .readOnly(false)
      .attributes(attribute)
      .authorisations($up.getSkillCodes())
      .build());
      logMsg("Rule : iac_task_supervisor_v12");
end;